### ISSUE TITLE
Empty case defaults to unit

### ISSUE THREAD

**Issue by dhil** [links-lang/links#103]
An empty case expression defaults to unit. For example:
```javascript
links> switch (Bar) { 
                 case Foo -> 
                 case Bar -> print("Hello") 
           };
Hello
() : ()
```
Is this intended? This "feature" seems rather useless to me.

**Comment by dhil** [comment]
I will fix this when I come around to do #57.

**Comment by dhil** [comment]
After studying the grammer in [parser.mly](https://github.com/links-lang/links/tree/master/core/parser.mly) I understand why Links currently exhibits this behaviour. This is because the production rules for `case` and `block_contents`
```
case:
| CASE pattern RARROW block_contents { $2, block ~ppos:$loc($4) $4 }

block_contents:
| ...
| /* empty */ { ([], with_pos $loc (TupleLit [])) }
```
The expansion of `block_contents` may be the empty string, in which case it is interpreted as a nullary tuple literal.

So it has little to nothing to do with #57. I do not think this is bug per see, but rather I think it is a questionable design decision. When we refactor the parser and/or change the grammar or syntax of Links we may want to revisit whether we want to support this special case.

**Comment by SimonJF** [comment]
Ran into this today and was mightily confused for a second. I think this should be a parse error, and will make the necessary changes unless others object.

**Comment by dhil** [comment]
> Ran into this today and was mightily confused for a second. I think this should be a parse error, and will make the necessary changes unless others object.

I think you need to be careful. The change would be rather pervasive. Also, you may have to make the empty block `{ }` a parse error, which means `fun() { }` would be a parse error. The whole parser logic regarding implicit units is rather intricate.

**Comment by SimonJF** [comment]
Perhaps this is one for the Links developer meeting next week.

**Comment by dhil** [comment]
> Perhaps this is one for the Links developer meeting next week.

Just for the record, I am in favour of getting rid of the implicit units.

**Comment by jamescheney** [comment]
This issue seems related to the proposal to get rid of optional semicolons at the end of blocks (#900).  However, this behavior arises because of the line https://github.com/links-lang/links/blob/faa49cd09cc20429122c9def648b25cc3cab991b/core/parser.mly#L696

which allows `block_contents` to appear on the RHS of a `case -> ` branch *without* surrounding braces.  This is, I suppose, to avoid even more curly braces.  But since block_contents also matches an empty token sequence we get the implicit unit behavior, which is undesirable.

I think it would be reasonable to require some explicit content to be matched on the RHS of a case branch.  One way to force this (without resulting in many extra curly braces) could be to require the RHS to be `exp`; then the common case of immediately returning an expression will still parse, but braces will be needed if there is a sequence of bindings/expressions.  Returning unit will have to be done explicitly by writing () or {} or some other unit-valued expression.

**Comment by jamescheney** [comment]
Having just tried the idea of restricting the body of a `case` to be an `exp`, it seems that the more permissive syntax is used in only a few tests, but causes almost every example in `typecheck_examples.tests` to fail.  So adopting this change would require a large number of changes.  Moreover the curly braces are strictly speaking redundant since we can always tell when a case block ends (either by seeing the next `case`, or the `}` ending the whole switch block).

An alternative that might be a bit lighter-weight would be to duplicate the `block_contents' production to something like `case_contents`, and simply leave off the case that allows a `case_contents` to be empty and default to unit.  I like this idea better than manually adding hundreds of curly braces to the examples.
