### ISSUE TITLE
Xml type bug

### ISSUE THREAD

**Issue by vcgalpin** [links-lang/links#1037]
Output from Links REPL 0.9.3
```
Welcome to Links version 0.9.3 (Burghmuirhead)
links> var z = <a><a1>A1</a1><a2>A2</a2></a>;
Finishing process MAIN
z = <a><a1>A1</a1><a2>A2</a2></a> : Xml
links> var z_children = childNodes(z);
Finishing process MAIN
z_children = <a1>A1</a1><a2>A2</a2> : Xml
links> var z_grandchildren = childNodes(z_children);
***: Internal Error in lib.ml (Please report as a bug): Runtime type error: non-XML given to childNodes.
This should not happen if the type system / checker is correct. Please file a bug report.
```

**Comment by dhil** [comment]
The last call to `childNodes` is given the value
```
`List ([`XML ((Value.Node ("a1", [(Value.Text "A1")])));
         `XML ((Value.Node ("a2", [(Value.Text "A2")])))]).
```
The implementation of `childNodes` expects only singleton lists.

What is the intended semantics here? It is not clear to me how `childNodes` should behave here other than throwing an error (should be something else than an internal error, I think).

**Comment by jamescheney** [comment]
`childNodes` should probably have type `XmlItem -> `Xml`, and its implementation should leave out the list constructor on its argument, since (at least in the current implementation) it only makes sense to get the child nodes of an individual element.  Of course, if what you want to call it on is an `Xml` (which is a list of `XmlItem`s) then you need to figure out how to get the `XmlItem` you want to call `childNodes` on.  Alternatively, we could generalize `childNodes` to work on `Xml` by mapping it over all the `XmlItem`s in its argument and concatenating them.  Then things like what Vashti wrote would work.  I see no particular downside to this, but this bug is a whiff of the bad code smell I think still wafts around the current approach to XML.

Vashti, without changing the implementation of `childNodes` you can get the behavior you seem to want by defining 
```
fun betterChildNodes(x: Xml) { 
  for (y <- x) childNodes([y])
}
```

**Comment by jamescheney** [comment]
There are no tests or examples that I can see that exercise `childNodes`, so I suspect it would not break anything to specialize its input type to `XmlItem` or to generalize its implementation so that it deals with arbitrary lists.  The latter is probably more consistent with idiomatic Links usage where we usually use `Xml` for a single-element sequence.  For some reason, `getChildNodes` appears to be identical to `childNodes`, so we should change that too.

**Comment by vcgalpin** [comment]
I see there is syntax for an XML forest (https://links-lang.org/quick-help.html#XML-Quasiquotes)

> To introduce a forest of XML nodes that have no mutually enclosing XML element, use the special <#>...</#> syntax

This suggests to me that non-singleton lists of XmItem were needed at some time?  Since I'm currently working on XML document curation and planning to use the built-in Xml type (which I should perhaps reconsider), I may be reporting more XML problems.

**Comment by dhil** [comment]
> For some reason, `getChildNodes` appears to be identical to `childNodes`, so we should change that too.

I guess the XML integration is warranted a clean up.

> childNodes should probably have type XmlItem -> Xml, and its implementation should leave out the list constructor on its argument, [...]

Sounds reasonable to me.

**Comment by jamescheney** [comment]
I will give it a try, but I suspect that the second suggestion (generalizing `childNodes` to handle arbitrary `Xml` inputs, not just singletons) will be nicer for now, because it is more consistent with Links's current design which blurs the distinction between `XmlItem` and `Xml = [XmlItem]`, for example by giving you a `Xml` when you type a single element.  This design has the weird feature that there is no way to directly write an `XmlItem`, to get one you have to write a singleton `Xml` literal and then take the head of it as a list.  Another potentially confusing feature is that a list of `XmlItems` (i.e. an `Xml`) is printed without `<#>...</#>` tags, but to read it back in, these tags are needed.  (e.g. the value of `z_children` printed out in @vcgalpin's example does not round trip through the parser).

Links's design is due a cleanup but for the moment I'm inclined to take the path of least resistance, generalize the library function behavior while keeping the type as is and make a note to revisit this later whenever we actually get around to such a cleanup, rather than add an idiosyncrasy.

**Comment by slindley** [comment]
Related issues: #46 and #122

XML / HTML support could certainly do with some attention. The current design is not really coherent. In the meantime if we're just doing quick fixes then I'd by default err on the side of returning an error if some expected invariant is violated rather than overloading behaviour - though if that approach gets in the way of implementing a particular application that @vcgalpin is working on then we should still consider changing the semantics.

Though `Xml` is a type alias for `[XmlNode]` there are some places where it is implicitly assumed that an input to a function expecting a value of type `Xml` is a singleton list.
