### ISSUE TITLE
Alternative Package Managers?

### ISSUE THREAD

**Issue by alana92** [links-lang/links#1064]
Are there package managers other than OCaml that would allow you to install Links? Preferably one that works on an Windows operating system? I've tried installing the unofficial OCaml windows version that installs through Cygwin, but it doesn't seem to work either.

**Comment by jamescheney** [comment]
Currently the only package manager for which we package links distributions is OPAM, thus Links inherits whatever weaknesses OPAM (and OCaml) have w.r.t. Windows support.  We don't have more resources than the OCaml community does generally to improve how well OCaml / OPAM works under Windows.  The other approaches listed here may help: https://ocaml.org/docs/install.html#Windows

in particular, WSL seems potentially worth a try if you jsut want to try things out, so that the Linux-binary issue is not a problem.  Alterantively firing up VirtualBox with a Linux distribution, as described in the tutorial instructions

https://github.com/links-lang/links-tutorial

 might be worth a shot.  (This reminds me that with a new version released recently it is probably time to check whether the tutorial instructions need updating.)

**Comment by alana92** [comment]
Thanks James. I think I'll try setting it up with Windows subsystem for Linux and see how that goes.

**Comment by dhil** [comment]
WSL should do the trick nicely. I am closing this issue.
