### ISSUE TITLE
Setting up Postgres Database Example

### ISSUE THREAD

**Issue by alana92** [links-lang/links#1066]
I'm working my way through the installation instructions, but cannot seem to run the example with database. I have managed to run the example without a database. I've installed PostgreSQL with an executable downloaded from their website (including setting up a password for the default superuser called `postgres`), so I can also access the pgAdmin dashboard. 

So, the connection for PostgresSQL 14 in pgAdmin looks like this:

![image](https://user-images.githubusercontent.com/27347212/140729947-dc354c9c-09c2-4748-a544-4ba968b4d8b8.png)

I've also edited the config file in `$OPAM_SWITCH_PREFIX/etc/links`, it currently looks like this:

```
jsliburl=/lib/js
jslibdir=$OPAM_SWITCH_PREFIX/lib/links/js
stdlib_path=$OPAM_SWITCH_PREFIX/lib/links/stdlib
database_driver=postgresql
database_args=localhost:5432:postgres:(password goes here)
```

I wasn't entirely sure if the path variable mentioned at the end of step 3 should be added to this specific file as well? Referring to this one:

`path=$OPAM_SWITCH_PREFIX/share/links/examples,$OPAM_SWITCH_PREFIX/share/links/examples/games,$OPAM_SWITCH_PREFIX/share/links/examples/dictionary`

Also, I get stuck at the isntructions at the beginning of step 3 (creating appropriate databases).  If I try to run the `createdbs` file with `linx` operator I get this error message:

```
***: Parse error: createdbs:2

  for f in `ls *.sql`; do createdb ${f%.sql}; done
        ^

```
 

Finally, if I try to run the example anyway with this command:

`$ linx --path=$OPAM_SWITCH_PREFIX/share/links/examples --path=$OPAM_SWITCH_PREFIX/share/links/examples/games --path=$OPAM_SWITCH_PREFIX/share/links/examples/dictionary $OPAM_SWITCH_PREFIX/share/links/examples/webserver/examples.links`

I get the following error:

```
***: Fatal error : PostgreSQL returned error: Connection failure: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
```

Any advice would be much appreciated.

**Comment by jamescheney** [comment]
I assume you are trying to follow the instructions in INSTALL.md.  These are a little high-level and assume a fair amount of background knowledge about how to setup postgres so that local password-based connections are allowed for the account you want to use with Links, which can also vary from installation to installation (and I don't think anyone has tried postgres 14 yet so there may be a new issue there, as there was going from 11 to 12).  It's probably not a terrific idea to connect from links as the `postgres` user (which has unlimited rights) and Postgres may be configured by default not to allow password connections for the `postgres` user.  (If you're new to Postgres setup then it's also important to know that the `postgres` user account that the OS knows about is different from, and usually a different password, from the Postgres user account `postgres`.) 

I'd suggest trying the more detailed instructions here which outline how to create a non-privileged database account for Links to use to connect:

https://github.com/links-lang/links/wiki/Database-setup

Alternatively, you could follow the approach described in the tutorial, which uses sqlite3 (https://github.com/links-lang/links-tutorial), but this may not mae it easy to run the standard database examples.   A further caveat is that all  of these have the tendency to drift out of sync with newer versions of Links, because we haven't been being very disciplined about checking that everything still works as described.

Some specific answers:

the `path` variable shouldn't affect the database configuration/connection at all, it merely saves you having to write the equivalent path stuff on the command line.

in step 3, the `createdbs` script is not a Links program, but a (bash) shell script.  So in a standard Linux or Unix environment you should be able to just run it:
```
./createdbs
```
or 
```
bash createdbs
```

**Comment by dhil** [comment]
What operating system and shell environment are you using?

Depending on your use-case, I'd suggest you modify the `pg_hba.conf` to allow trust-based authentication for local connections, meaning you wont need to use a password to connect to the database from your Links application. For example, supposing your database user is named `links`, then you'll have to add the following lines to the file **right after** the `local   all             postgres                                peer` entry:
```
# trust-based authentication for user links
local   all             links                                   trust
host    all             links           samehost                trust
```
On a Debian-based system the `pg_hba.conf` can be typically be found under `/etc/postgresql/<version number>/main/`.

**Comment by alana92** [comment]
Thank you for all the comments and suggestions, will try them out and revert.

Just to say, I'm using primarily Ubuntu terminal (in Windows Terminal) with WSL (Windows subsystem for Linux), because I needed it to install Opam (package manager) and Links through Opam.

**Comment by alana92** [comment]
Ok, so I've been trying the [database setup instructions](https://github.com/links-lang/links/wiki/Database-setup) and everything worked, but am now getting stuck at step 4 with this error message:

`^[[Dpsql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?`

I've also uninstalled PostgresQL 14 and installed PostgresQL 12 instead, but it doesn't seem to make a difference. Is there perhaps something I can install or change on Stack Builder that comes along with the PostgresQL installation? I.e. Add-ons, tools, database drivers etc.

**Comment by jamescheney** [comment]
I see you've edited to include that you have tried both installing Postgres within Ubuntu (which should normally work straightforwardly) as well as trying to connect to the Windows install (which I guess could require some additional work to cross-map the Ubuntu and Windows ports).  If you're still getting this error, when trying to run psql to connect to Postgres that's installed inside Ubuntu, then this is nothing to do with Links per se, but may just be because whatever Postgres installer you are using did not start Postgres for you (or started it in a nonstandard way, for example at a different port).  If that's the case, something like this askubuntu discussion may help:

https://askubuntu.com/questions/1206416/how-to-start-postgresql

**Comment by rudihorn** [comment]
The `psql` command will try to connect using the unix socket mentioned in the error message first. Depending on your setup (especially if the PostgreSQL is running in Windows non-WSL) it will not support unix sockets. You can use `-h <hostname> -U <username>` to connect via TCP instead (optionally `-W` makes it ask for a password). These options are listed in the `psql` command man page: https://linux.die.net/man/1/psql

The other thing you should check is what the exact setup is of WSL with regards to networking. https://docs.microsoft.com/en-us/windows/wsl/networking seems to indicate there are different versions where either the loopback address is shared between WSL and the host and one where they are seperate. It would be best for you to just pick between either hosting postgres in WSL or on the windows host, and then figure out how to access it from there (hosting it in WSL will probably be more straightforward).

**Comment by alana92** [comment]
@jamescheney I seem to be able to start postgres with  `sudo service postgresql start 12`, but when I run `sudo service postgresql status 12` I get this feedback:

```
12/main (port 5433): online
14/main (port 5432): down
```
@rudihorn I've installed it and run it via ubuntu now. Running `sudo netstat -anp | grep 5432` after I installed `net-tools` doesn't seem to provoke any reaction at all. If I leave out `sudo` it gives: `No info could be read for "-p": geteuid()=1000`

**Comment by rudihorn** [comment]
Ah your output explains a lot. It seems that port 5432 is used by your PGSQL version 14 installation, while 5433 is used by PGSQL 12. I think running commands of the form `psql -p 5433 -c <Do something>` should work / use the correct unix socket if I understand the manual correctly.

**Comment by alana92** [comment]
@rudihorn Thank you so much, it worked! Continuing installation.

**Comment by alana92** [comment]
@jamescheney I seem to be getting parsing error for `insert test  values (i, s) [(i=1, s="one")];` from Step 7 of [database setup](https://github.com/links-lang/links/wiki/Database-setup):

```
***: Runtime error: An error occurred executing the query insert into test ("i","s") VALUES (1,'one'): Fatal_error : The server's response was not understood (ERROR:  relation "test" does not exist
LINE 1: insert into test ("i","s") VALUES (1,'one')
                    ^
```
Though when I did the previous line `var test = table "test" with (i : Int, s : String) from db;` it just gave me `test = (table test) : TableHandle((i:Int,s:String),(i:Int,s:String),(i:Int,s:String))`

Is it just syntax error you think?

**Comment by alana92** [comment]
Ok, so I finished the database setup as per [instructions](https://github.com/links-lang/links/wiki/Database-setup), but now when I run [the example with the postgres database](https://github.com/links-lang/links/blob/master/INSTALL.md) I get this `***: Fatal error : PostgreSQL returned error: Connection failure: connection to server at "localhost" (127.0.0.1), port 5433 failed: FATAL:  database "citations" does not exist`.

**Comment by jamescheney** [comment]
The error message means that Postgres is returning an error "FATAL: database "citations" does not exist".  For the examples in INSTALL.md that use the larger databases `citations` and `dictionary` to work, the data dumps in the links-data repository need to be loaded too, as explained in this line of INSTALL.md:

>Postgres data dumps for the larger databases (citations and dictionary) can be obtained from a separate repository: https://github.com/links-lang/links-data.

**Comment by alana92** [comment]
@jamescheney Perfect, so I'd just install that with `opam install links-data`?

**Comment by jamescheney** [comment]
I'm afraid there isn't an OPAM package, just the git repository (and the readme there is pretty minimal).  What needs to happen is for you to get the sql scripts from the `links-data` repository onto your system somewhere, e.g. by doing a git clone, and then running them through psql in a sensible order.  I think something like this should work:
```
psql -f citations.sql
psql -f dictionary.sql
```
though you may need to add other command line options for database, username, password etc. to get things to go into the right place.  

The documentation how to do this should be updated/filled in anyway.

**Comment by alana92** [comment]
@jamescheney I managed to get them installed and made sure that the account I'm using in the config file has permission to access. Running the example now seems to work initially, but I'm getting this feedback on my browser when I open one of the specific database version example from the landing page:

`***: Runtime error: An error occurred executing the query select (t9827."name") as "name",(t9827."i") as "order_1" from "items" as t9827 order by order_1: Fatal_error : The server's response was not understood (ERROR: permission denied for table items )`

Also, I saw that PostgresSQL has training manual ebooks you can buy for the different versions of the program, are they good intros? And also, are there any other books I should check with regards to developing in Links more broadly?

**Comment by jamescheney** [comment]
This error looks likely to be because the `items` table has been created by a different database user than the one you are using to connect from Links programs (the "Links user"), and the Links user hasn't been granted access to this table.  You can check if this is the problem by trying to log in as the Links user and access the corresponding database / table manually using `psql -u ... -d ...` and seeing if you get the same error if you try to do `select * from items` manually.   If so, then get out of psql, log in as `postgres`, and give the Links user the needed permissions on the needed database/table as described in step 4 of the database instructions (https://github.com/links-lang/links/wiki/Database-setup).

(All of this messing around with permissions and users makes me think even more that we should update the instructions to suggest using sqlite3 as a default, since there's a lot less of this administrivia to deal with for that, so people not already familiar with postgres or mysql don't have to learn it first before playing with Links.)

Regarding postgres manuals/documentation, I generally get by with searching the online manual (https://www.postgresql.org/docs/) and can't comment on the usefulness of specific books.  There are no books about Links programming per se, and since it's under active development/evolution as an academic research project, it's a moving target, so even what documentation we do have is outdated and incomplete.

There is a mailing list (http://lists.inf.ed.ac.uk/mailman/listinfo/links-users) that most of us are on, which might make more sense to use for more routine questions than this issue discussion.  (though before closing this issue we should update the particular bits of documentation whose absence or vagueness led to your being stuck.)

**Comment by alana92** [comment]
Even after I've granted the links user access to all the current databases I still can't seem to access any of the tables when I log in as the links user. The response I get is:

```
winestore=> select * from items
winestore->
```

**Comment by jamescheney** [comment]
When sending commands to Postgres using psql you need to terminate them with a semicolon.  See https://chestofbooks.com/computers/databases/postgresql/practical-postgresql/Entering-queries-at-the-psql-prompt.html

**Comment by alana92** [comment]
Thanks. I just get `ERROR:  permission denied for table items` response. Tried redoing the permission commands with semicolons, but didn't help.

**Comment by jamescheney** [comment]
It's hard to guess what the problem might be and this appears to be a pure Postgres configuration issue.  For example it could be that since you've already created the tables, you need to grant the `links` user access to each already-created table and not just the containing database.  Without more information (or being able to look at the permissions manually) I can't be sure.

One way to make progress could be to delete everything, re-create the `links` database and grant access to it by the `links` user, and then see if you can create the tables again acting as that user, e.g. by manually running the .sql scripts using `psql -d <links_database> -U <links_user> -f <script>.sql`.  So if the links user and database are both called `links` you could do:
```
psql -d links -U links citations.sql
```

**Comment by jamescheney** [comment]
Another possibility which the interaction above makes me think might be relevant is to check whether the "database" is the same when you log in as postgres and as the links user.  In the above comment, the beginning of the prompt `winestore=>` I think means that you are logged into postgres using the `winestore` database (which perhaps confusingly is SQL's / Postgres's name for a top-level collection of tables, a database server can contain many databases, but basically it's a namespace for tables).  If when you log in as the postgres user you are in a different database, say "other_database", that happens to contain an `items` table, you could have granted the Links user access to that but it's a different table (`other_database.items`) from the `items` table in `winestore`.  Not sure if this is helpful, but my suggestion of deleting and re-creating the tables as the links user in a specific database might fix this also.

**Comment by alana92** [comment]
I finally got it working! When I did `psql -d links -U links citations.sql` postgres just ignored `citations.sql`, but I was able to log in as the postgres superuser and manually alter the owner of each database and table (you have to do the one by one) and it worked! Thank you!
