### ISSUE TITLE
Self-hosted virtual DOM

### ISSUE THREAD

**Issue by dhil** [links-lang/links#1102]
We should lift the virtual DOM logic into Links in order to keep the JavaScript runtime minimal. As a backend the virtual DOM in Links could make use of `DocumentFragment` (c.f. https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment).

**Comment by SimonJF** [comment]
I may be misunderstanding precisely what you're proposing, but I must admit this does make me a little uneasy. I'm onboard with the JS runtime being minimal, but MVU is after all external to the core JSLib, and languages like Elm do rely on external JS code for the virtual DOM.

I suppose one reason I'm uneasy about this is performance (although I don't claim the current implementation is performant anyway). If we do go down this route, could we ensure the code is compiled such that it runs atomically? It would be strange to context-switch midway through the diffing code for example.

**Comment by slindley** [comment]
I mostly agree with @SimonJF and disagree with @dhil here.

For libraries such as MVU performance (of potentially computationally intensive things like DOM diffing at least) is key. It would be an interesting exercise to reimplement this functionality in Links, but it is not a priority and could cause us more problems than it is worth.

In any case, we must explicitly support running existing JS libraries and calls to JavaScript code will necessarily be run atomically without the opportunity to yield. This is to be expected. It should not normally be a problem as existing JavaScript library API calls need to be responsive otherwise web apps would grind to a halt.
