### ISSUE TITLE
Option or Maybe?

### ISSUE THREAD

**Issue by dhil** [links-lang/links#1116]
The prelude and runtime make inconsistent use of optional data types. In some place we use a `Maybe(a) = [|Just:a|Nothing|]` type, whereas in others we use `Option(a) = [|Some:a|None|]`. We should pick either and stick to it throughout Links. I suggest we have a brief discussion about this matter and make a swift decision on Monday.

This will be a breaking change.

**Comment by ezrakilty** [comment]
Historical note: at the beginning, Jeremy really preferred the Haskell style, Just/Nothing, saying that "Nothing" was more natural English. I preferred the ML style, because Some/None have the same number of letters. I suppose we put our own preferences into the prelude in different places. In other ways, I used to advocate the ML point of view while Jeremy did the Haskell.

Ironically, he now works on OCaml, and I do all my hacking in Haskell.

**Comment by dhil** [comment]
I had a conversation with @slindley the other day about this "issue". Sam asked me who introduced either; my guess off the cuff was you and @yallop, though, apparently I had it wrong way around -- I thought Jeremy had introduced `Option` and you had introduced `Maybe`. Thanks for the correction and historical note, @ezrakilty!

**Comment by dhil** [comment]
`Maybe` won.
