### ISSUE TITLE
Some questions about your work :)

### ISSUE THREAD

**Issue by lidorcg** [links-lang/links#1166]
Hello,

First of all, I'm sorry if this is the wrong channel, I wanted to contact you about your work and couldn't find a better way, if there is please feel free to point me to it and close this issue.

My name is Lidor and I'm a developer from a company called [SPIRITT](https://spiritt.io/) and we are all about cracking the model of web applications. Our research led me to the paper: [Incremental Relational Lenses](https://arxiv.org/abs/1807.01948), and from there to this project.

Our goals seem to have a lot in common and your work seem to tackle some extremely fundamental issues, I'd like to connect and learn more from you.

P.S
I have more specific topics I'd love to get some tips from you, I just wanted to say hello first :)

**Comment by jamescheney** [comment]
Hi Lidor,

thanks for your interest. Probably I am the most relevant person to talk to about that paper since @rudihorn and @rolyp are working elsewhere on other things nowadays.  @SimonJF has also worked on another relevant paper [Language-Integrated Updatable Views](https://arxiv.org/abs/2003.02191) which might or might not be relevant (it is more about language design than the underlying data synchronization problems).

I'm happy to disccuss further either in this issue in case there are other things that might be more worthwhile for you to speak to others about, but as that's not really what issues are for I'm also happy going to email and then I could point you to others as apporpriate.  My email address is buried in the paper you mentioned as well as on my University homepage.

**Comment by lidorcg** [comment]
Thank you very much James, I'll email you soon so we can continue our conversation 😊

**Comment by rudihorn** [comment]
Hi @lidorcg, I'm also happy to answer any questions there may be, even though I do have limited time to work on this these days.
