### ISSUE TITLE
Question: Mobile processes and RPC calls

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#140]
I'm still a little confused as to the notion (and extent) of "mobile processes".

I understand that processes spawned in realpages mode using spawnClient need to be serialised and spawned at the client. But how about if the client then makes an RPC call, like so?

```
fun procLoop() {
  receive {
    case Hello() -> debug ("Received 'hello'")
    case Hi() -> debug ("Received 'hi'")
  };
  procLoop()
}

fun serverCall(pid) server {
  pid ! Hi()
}


fun mainPage(_) {
  var pid = spawnClient { procLoop() };
  pid ! Hello();
  page
    <html>
      <body>
        <h1>"Hi!"</h1>
        <form><button l:onclick="{serverCall(pid)}">Click me</button></form>
      </body>
    </html>
}

fun main() {
  addRoute("/", mainPage);
  servePages()
}

main()
```

Currently this doesn't work because of a PID marshalling error (it's just sent as an integer as opposed to a first-class PID). 

My guess is that it should work since there appears to be a chunk of machinery in place such as `pop_all_messages_for()`. That is, my intuition is that the process should be spawned on the client, initialised with the "Hello()" message. Subsequently, when the button is clicked, the "Hi()" message should be added to the MQ server-side, and serialised in the ClientReturn response, after which the JS runtime adds it to the end of the queue.

Alas, I'm still not completely clear about what is and isn't allowed with webserver / realpages semantics, so thought I'd best check before fixing.

**Comment by slindley** [comment]
This is not expected to work at the moment because it would require the server sending messages to a process on the client. The only scenario in which that currently works is *before* a process spawned on the server with `spawnClient` has been sent to the client. Your code goes back to the server *after* execution has moved to the client (it is invoked by clicking a button!).

Of course, we do want to support client -> server and server -> client communication, but the only way of doing that at the moment is through RPC calls.
