### ISSUE TITLE
default route?

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#151]
"Nope" is unhelpful.  I would like to be able to do something like this:

```
setDefaultRoute(fun (s) {<b>Route {stringToXml s} not handled</b>}) 
```

to set a handler for any routes not handled by `addRoute` or `addStaticRoute`.

Also, the ability to redirect to another route would be nice (e.g. to send any mistyped URLs to the toplevel page after an error message).

**Comment by jgbm** [comment]
You can already get the behavior you want with the current routing functions, so long as you configure them correctly.  In particular, if you do
```
addRoute("/", fun(s) {<b>Route {stringToXml s} not handled</b>"})
```
then that route will handle all requests that do not match a more specific later entry in the routing table.  I think there are already Links functions to handle redirection.

One thing that is a bit nonsense about the current approach is that it depends on the order in which routes are added to the routing table, not on the relative specificity of their paths.  So, if you add that route AFTER other routes, it will take precedence over them.  This is unpleasant.

My preference would be to change the latter behavior so that the routing table is more sensibly ordered, but otherwise not add special primitives to handle the default case.  Does that make sense?

**Comment by jamescheney** [comment]
Yes, what I was thinking was that "setDefaultRoute" would only be used if all else fails, so the order of adding it to the table would not matter, and one could set it later (dynamically) without killing all of the existing routes.  If there's some equivalent way to do that without changing the API (e.g. treating the routes as a trie and dispatching to the most specific route handler) that is of course fine too.

**Comment by SimonJF** [comment]
Closing since #157 was merged.
