### ISSUE TITLE
Function duplication required to compile

### ISSUE THREAD

**Issue by elordin** [links-lang/links#173]
[This file](https://gist.github.com/elordin/ca403d19707f1b66bbf31841b23ec595) requires the identical duplicate of function `listRenderFun1` (line 311 & 349) to be passed to the `uselet` function (line 393 / 126).

Lines 125, 137, 163, 386 ff. are the alternative version with only one copy of the render function, that is then called in two separate locations (137, 163).

Using that version results in the error 
```
listUselet.links:163: Type error: The function
    `view'
has type
    `((b) ~a~> ()) {:c|d}~> (e) {:c|d}~> Xml'
while the arguments passed to it have types
    `(b) ~a~> ()'
and the currently allowed effects are
    `|wild'
In expression: view(send).
```

**Comment by jamescheney** [comment]
I think this is a correct, but not well-explained, type error.

The problem is you are calling view in two places, one of which is in a freshly spawned different process context which can "hear" messages (the :c type annotation in {:c|d}~>) and the other cannot - since `uselet` is called at the toplevel of the program which cannot receive messages.  (hence, the "wild" currently allowed effect describes the second call).  This is morally like if you did this in Haskell/ML:

```
foo :: (a -> a) -> (Int,Bool)
foo(f) = (f 42, f True)

foo(id)
```
i.e. just because f has a polymorphic type, doesn't mean you can use polymorphically on something of any type.  To get the behavior you want in Haskell (which optionally has higher-rank polymorphism) you have to do something like this:
```
foo :: (forall a. a -> a) -> (Int,Bool)
foo(f) = (f 42, f True)

foo(id)
```

Possily counterintuitively, "wild" does not mean anything can happen; it just means specific things that can't happen on the database are allowed.  So {hear:msg,wild} is a different effect than just {wild}.  

I think to handle this you'd need first-class effect polymorphism to quantify the type of "view" by its effect, so that it can be used either in a context with a "hear" effect or with no concurrency.   I seem to recall Sam saying something about first-class polymorphism being supported a while ago, but don't remember the details.  If it's supported, then my guess is to make it work you would have to write an explicit type quantifier; have a look at tests/polymorphism.tests for examples.

The good (?) news is that even without writing out the types with explicit "forall"s, you can at least work around to avoid the need to completely duplicate the code of listRenderFun, as follows:

```
sig listRenderFun : ((ListMessage) ~> ()) ~> (Model) ~> Xml
fun listRenderFun (send)(model) {
  <#>
    <style>
      ul {{
        font-family: sans-serif;
        margin: 1rem 0;
        padding: 0;
      }}

      li {{
        display: block;
        list-style-type: none;
        border-bottom: thin solid #ccc;
        padding: .5rem;
      }}

      li:last-child {{
        border: none;
      }}

      li:nth-of-type(2n) {{
        background-color: #eee;
      }}
    </style>
    <button l:onclick="{ send(AddItem) }">Add</button>
    <ul>
      {
        for (item <- model.items) {
          <#>
          <li>{ stringToXml(item.body) }</li>
          </#>
        }
      }
    </ul>
  </#>
}

fun listRenderFun1 (send)(model) { listRenderFun(send)(model) }
fun listRenderFun2 (send)(model) { listRenderFun(send)(model) }

var listUselet = uselet(
  "mylistelem",
  (value="", items=[ ]): Model,
  listUpdateFun,
  listRenderFun1,
  listRenderFun2
);
```

**Comment by dhil** [comment]
Yes, Links does indeed support first-class polymorphism. You are indeed correct that one has to use an explicit quantifier. For example
```links
links> sig foo : (forall a . (a) -e-> a) -e-> (Int, Bool) 
       fun foo(f) { (f(42), f(true)) };
foo = fun : (forall a.(a) -b-> a) -b-> (Int, Bool)
links> foo(id);
(42, true) : (Int, Bool)
```

**Comment by elordin** [comment]
Conceptually this is clear. (I suspected something of that sort, which is why this doesn't have the bug label.)

Syntactically not so much though.

How exactly do I unify the two signatures of `view`
```
((b) ~a~> ()) {:c|d}~> (e::Any) {:c|d}~> Xml
((b) ~a~> ()) {    }~> (e::Any) {    }~> Xml
```


Forcing a user to duplicate the render function and pass it twice obviously shouldn't be an option. That would be akin to 
```Haskell
-- | 'map' f g xs is the list obtained by applying f to each element of xs ... or g ... as g and f should do the exact same thing
map :: (a -> b) -> (a -> b) -> [a] -> [b]
```

**Comment by jamescheney** [comment]
Sorry, I was a little vague.  In Links, you can have variables where effects go - i.e. effects are types of kind Row and you can quantify over variables of this kind.  So I *think* something like this should work:

```
forall z::Row. ((b) ~a~> ()) {z}~> (e::Any) {z}~> Xml
```
since you can instantiate the `z` with either `:c|d` (I can hear something) or `wild|_` (I can't hear something, but potentially do non-databaseable things).

However, Links (like most languages with first-class polymorphism) won't try to guess where to put `forall` in a type to make unification work.  So you would need to ascribe the above type to "view" as part of a larger type signature for "uselet", which may be a pain.  Decomposing its type into more manageable pieces using type abbreviations may help with this.

**Comment by elordin** [comment]
That I did indeed try but unfortunately to little success:
```
`view' has type 
    `((a) ~b~> ()) {wild,z}-> (c) {wild,z}-> Xml' while the arguments passed to it have types
     `(a) ~b~> ()'
and the currently allowed effects are
    `wild|hear:d::Any|e::Any'
```

```
`view' has type
    `((a) ~b~> ()) {wild,z}-> (c) {wild,z}-> Xml' while the arguments passed to it have types
     `(a) ~b~> ()'
and the currently allowed effects are
    `|wild'
```
(with the source line with the top-level call before the in-process call and vice versa respectively)


Furthermore, I created this reduced version of the code:
```
sig p : ((String) {:[|Foo|]|a}~> Xml) {:[|Foo|]|a}~> Xml
fun p (f) {

  fun handler () {
    receive {
      case Foo -> {
        var xml = f("bar");
        var node = getNodeById("t");
        replaceNode(xml, node);
        handler()
      }
    }
  }

  var h = spawnClient { handler() };

  <button l:onclick="{ h ! Foo }" id="t">
    { f("foo") }
  </button>
}
```
that has the call to `f` at top-level and inside a spawned process. 
This compiles just fine and even without annotation infers the type above.

**Comment by dhil** [comment]
I think you have to write
```
forall z::Row. ((b) ~a~> ()) { |z}~> (e::Any) { |z}~> Xml
```
note the space and pipe in the effect row.

**Comment by elordin** [comment]
Yes, according to the _"Out-of-date basic documentation"_ `~X~>` desugars to `{|X}~>`

Unfortunately even with space and pipe it still results in the almost identical error
```
`view' has type
    `((a) ~b~> ()) ~c~> (d) ~c~> Xml' while the arguments passed to it have types
     `(a) ~b~> ()'
and the currently allowed effects are
    `wild|hear:e::Any|f::Any'

`view' has type
    `((a) ~b~> ()) ~c~> (d) ~c~> Xml' while the arguments passed to it have types
     `(a) ~b~> ()'
and the currently allowed effects are
    `|wild'
```

**Comment by jamescheney** [comment]
The above error message looks like what you would get if you abstracted the type of effect `c` of the view function, but the type variable was still bound at the level of the overall type of `uselet`, not localized to the view function's type.  But it may be that Links's error messages don't print out the quantifiers.

Can you put the exact code you are running that produces the above error online somewhere?

**Comment by elordin** [comment]
Moving the quantifier from the top
```Haskell
sig uselet : forall z :: Row. (
    String,
   model,
   UpdateFunction(model, msg),
   ((e) ~> ())  { |z}~> (model) { |z}~> Xml # ViewFunction(model)
 ) -> (
   AddressSource,
   Services,
   Dispatcher
 ) {}~> (
   Xml,
   AddressSource
 )
```
to the single argument
```Haskell
sig uselet : (
    String,
   model,
   UpdateFunction(model, msg),
   forall z :: Row. ((e) ~> ())  { |z}~> (model) { |z}~> Xml # ViewFunction(model)
 ) -> (
   AddressSource,
   Services,
   Dispatcher
 ) {}~> (
   Xml,
   AddressSource
 )
```
did indeed fix that error. (Thanks also to @SimonJF, @jgbm )

With that and a few more changes it now actually does work!
```Haskell
sig uselet : (
  String,
  model,
  forall y :: Row, z :: Row. (b::Any) { |y}~> (model, msg) { |z}~> model,
  forall z :: Row. ((e) ~> ())  { |z}~> (model) { |z}~> Xml
) -> (
  AddressSource,
  b::Any,
  Dispatcher
) {}~> (
  Xml,
  AddressSource
)
```
