### ISSUE TITLE
Annotating the inferred type breaks code

### ISSUE THREAD

**Issue by elordin** [links-lang/links#174]
See [this file](https://gist.github.com/elordin/41729e3867738ca99e438b3a70280f96)

Evaluating it gives the output
```
fun : Uselet (Model,ListMessage)
```
which should be `show(listUselet)` as `listUselet` is the final expression.

Annotating `listUselet` with the printed type `Uselet (Model, ListMessage)` (see comment in [line 322](https://gist.github.com/elordin/41729e3867738ca99e438b3a70280f96#file-listuselet_2-links-L322) ) results in the rather odd error
```
Type error: The inferred type of the expression
    `uselet("mylistelem", (value="", items=[ ]): Model, listUpdateFun, listRenderFun)'
is
    `Uselet (Model,ListMessage)'
but it is annotated with type
    `Uselet (Model,ListMessage)'
In expression: 
    uselet("mylistelem", (value="", items=[ ]): Model, listUpdateFun, listRenderFun) : Uselet (Model,ListMessage).
```

**Comment by jamescheney** [comment]
I just had a look at this and as of Links 0.9 the given example program doesn't typecheck anymore, for various reasons.  I'm inclined to close this since I suspect the original problem was due to the earlier ad hoc treatment of first-class polymorphism which has now been replaced.  In particular I suspect getting the uselet example to work again will require adding some freezing or other constructs since the earlier version was using quantifiers nested inside other types.

Perhaps we could revert to an earlier version when this example worked, and slice it down.  However, that seems like it amy require reverting to earlier OCaml versions/libraries too.

If no one has another (smaller?) example of this problem then I think we should close this and open a new issue when/if we find another example of it.  @slindley, @frank-emrich ?

**Comment by slindley** [comment]
This example is pretty-much useless without being minimised anyway. Either someone should attempt to minimise it or it should be closed - probably the latter.

**Comment by jamescheney** [comment]
Closing.
