### ISSUE TITLE
No line number / position on error: Type alias applied with incorrect arity

### ISSUE THREAD

**Issue by elordin** [links-lang/links#184]
```
*** Fatal error : Type alias Alias applied with incorrect arity (a instead of b)
```

should give a position where the error occurred, preferably with filename, line and position

**Comment by jstolarek** [comment]
@dhil there was a suggestion during Links meeting that this might be related to your work on module system. Is that the case? I am unassigning myself for the moment because I'm not actively working on fixing this.

**Comment by dhil** [comment]
@jstolarek we can probably fix this in the new module system patch.

**Comment by jamescheney** [comment]
Fixed by #528

**Comment by jstolarek** [comment]
Hmm... I was pretty sure I commented on this one somewhere in #528 but can't seem to find my comment now. Anyway, does #528 really fix #184? Meaning: is the error being raised in OP an actual internal error in the compiler (an equivalent of `assert false`) or is this an error message that should be displayed to the user to inform that her program is incorrect? If the former, then #184 was never really a bug, if the latter then I don't think #184 is fixed by #528.

**Comment by jamescheney** [comment]
I thought it was fixed by the change in `instantiate.ml` line 432:

``` 
-       failwith (Printf.sprintf
-                    "Type alias %s applied with incorrect arity (%d instead of %d)"
-                    name (List.length tyargs) (List.length vars))
+        internal_error (Printf.sprintf
+               "Type alias %s applied with incorrect arity (%d instead of %d). This should have been checked prior to instantiation."
+          name (List.length tyargs) (List.length vars))
```

Indeed, in the current version this now seems to do the right thing:

```
links> typename Foo(a,b) = (a,b);
Foo = a,b.(a, b)
links> fun bar(x:Foo(Int)) {x};
<stdin>:1: Arity mismatch: Type Foo expects 2 type arguments, but 1 arguments were provided. In: Foo(Int)
```

I guess that the error is caught earlier than the `instantiate.ml` one, though.  So hopefully that one is dead code now.

**Comment by SimonJF** [comment]
Good question, @jstolarek. @jamescheney is correct in saying that the error is caught earlier than in `instantiate.ml`:

https://github.com/links-lang/links/pull/528/files#diff-22ddaf26a647d1c52db61fb8076d2e6dR219

The reason that this is treated as an internal error is that the check should have been done prior to `instantiate.ml` -- if it hasn't been, then this is because the `instantiate` API has been misused somewhere (therefore this is treated as an internal error).

**Comment by jstolarek** [comment]
All is fine then. Sorry for raising a false alarm.

**Comment by SimonJF** [comment]
Not at all. I was wondering the same.

**Comment by jamescheney** [comment]
So I was right that this is closed, but for the wrong reason.  I'll take it! :)
