### ISSUE TITLE
Calls to client-side functions from server side

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#207]
we call a client-side (side-effecting) function such as `replaceNode` from a function marked as `server`, the right thing does not appear to happen.  For example changing line 6 of [this](https://github.com/links-lang/links-tutorial/blob/master/3_form_client/form_client.links) to make handleForm run on the client, seems to lead to the replaceNode call silently failing.  I can see in the web dev console that there are two trampolined calls from the server to the client (to perform `getNodeById` and then `replaceNode`) and it looks like the http response in each case is appropriate, but nothing actually happens.  

Leaving the location unspecified, or specifying `client`, works.  But I would expect this to either work if `server` is specified or to get an error message indicating that client-side functions cannot be called from server-side contexts.

**Comment by SimonJF** [comment]
It's trying to serialise a DOM reference. See the following:

```
var elem = document.getElementById("_lnameid__g129");
undefined
elem
<input value=​"foo" name=​"lname__g130" id=​"_lnameid__g129">​
JSON.stringify(elem);
"{}"
```

The actual call logic is fine; the issue is that the client tries to JSONise something which is innately not JSONisable (and thus seems to pick the empty object). Then, when making the second call, we try and pass this non-JSONisable reference back. The error then comes when the replaceNode logic tries to call `parentNode` on `{}`.

Anyway, this is fixable, I'll have a go at it.
