### ISSUE TITLE
recursive function type inference / signature issue

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#209]
# Input

The following simple (if contrived) program illustrates the problem:

```
sig f: ()~>()
fun f() { h() }

sig g : ()~>()
fun g(){ h() }

#sig h : () ~> ()
fun h(){
 replaceNode(<#>
    <a l:onclick="{f()}">F</a>
    <a l:onclick="{g()}">G</a>
  </#>,
  getNodeById("foo"))
}
```
Here, `f` and `g` are just aliases for a recursive call to `h`, while `h` performs a side-effect on the DOM tree embedding calls to `f` and `g` in click handlers.  (This is a simplified form of a larger program that actually does something useful with the same call pattern.)

# Desired output:
The program should typecheck if some or none of the (correct) type signatures are present.

# Actual output:
When the signature for `f` and `g` are given but the one for `h` is not (as above), there is a type error:

```
Type error: The recursive function definition has type
    `() ~a~> ()'
but its previously inferred type is
    `() ~b~> ()'
In expression: fun f() {
  h()
}.
```

However, for all 7 other possible configurations (i.e. whenever either `f` or `g` has a type signature, then `h` also has one)  then the program typechecks.

**Comment by elordin** [comment]
As so often, adding some `%` makes it typecheck:

```
sig f: () ~%~> ()
sig g : () ~%~> ()
```

It then manages to infer the type of `f`, `g`, and `h` to be `() ~> ()`, so giving that as type annotation really should work.

**Comment by slindley** [comment]
The XML stuff is clearly irrelevant to this example. The following code yields the same error.

    sig f: ()~>()
    fun f() { h() }
    
    sig g : ()~>()
    fun g(){ h() }
    
    #sig h : () ~> ()
    fun h(){
      f();
      g()
    }

To see what's going on it's worth adapting the code so that the polymorphism is in the values rather than the effects:

    sig f : (a) {}~> ()
    fun f(x) { h(x) }
    
    sig g : (b) {}~> ()
    fun g(x){ h(x) }
    
    #sig h : (c) {}~> ()
    fun h(x){
      f(x);
      g(x)
    }

This yields the following type error:

    Type error: The recursive function definition has type
        `(a) {}~> ()'
    but its previously inferred type is
        `(b) {}~> ()'
    In expression: fun f(x) { h(x) }.

This is not a bug but the intended behaviour. The reason for the error is that unannotated function definitions are typed monomorphically in the definitions of mutually recursive definitions (we do not guess polymorphism), but the polymorphic annotations on f and g require h to be polymorphic.

**Comment by jamescheney** [comment]
So this is a bug in error message printing, not in the typechecker.  The error message should explain the quantification.

**Comment by slindley** [comment]
No. This is not a bug. The error message is correct, if misleading. (Just because I'm able to work out the root cause of the error doesn't mean it's reasonable to expect the type checker to come up with the same diagnosis as me.) You may be able to improve it by carefully crafting appropriate gripers. I think that would be an enhancement rather than a bug fix.

It would be useful, and I think interesting, to improve error reporting in general, but I don't see anyone showing enthusiasm for doing that kind of work at the moment.

Another possible enhancement would be to come up with alternative heuristics for type inference in the presence of mutually recursive functions which might allow this particular example to type check.

A property that would be nice to hold: successful type inference is always preserved by adding correct type annotations to a program. This property doesn't hold for Links at the moment, and it certainly doesn't hold for languages like Haskell. It could perhaps be made to hold by using backtracking (first try to type check without type annotations), but I'm not sure if that's a good idea.

**Comment by jamescheney** [comment]
Potato, potahto.  The error message does not give any hint as to what the problem is, especially in the effect case where the effect variables are inserted by desugaring and were never written in the initial code.  Of course this is a well known problem with HM-style type inference.

**Comment by jamescheney** [comment]
It looks like I am the only one who is annoyed about this so closing.
