### ISSUE TITLE
Function return type cannot be qualified by module name.

### ISSUE THREAD

**Issue by elordin** [links-lang/links#225]
Consider the following example:
```
# one.links
typename One = [| Foo | Bar |];
```
```
# two.links
open One

sig foo : (One.One) ~> One.One
fun foo (a) {
  a
}
```
Results in 
```
*** Parse error: two.links:4
  sig foo : (One.One) ~> One.One
                              ^
```
whereas when omitting the module prefix it unsurprisingly gets confused by the identical module name:
```
*** Fatal error : Unbound type constructor One
```

**Comment by jamescheney** [comment]
I suggest we defer this to 0.7.3 and release 0.7.2 ASAP.

**Comment by jamescheney** [comment]
I'm happy with kicking this can down the road to > 0.7.3, given that @SimonJF is away in the real world this summer.

**Comment by dhil** [comment]
I think the proper solution is to implement a proper module system. I have been looking into this recently, and I am happy to talk more about this on an upcoming meeting.

**Comment by dhil** [comment]
The problem is syntax. The module system cannot use `.` for selection at the type level as long as session types are using `.` for sequencing. 

I suppose we want to use the same notation for selection at both the type level and term level. Currently, I am using a funny notation for selection in my current module system implementation, and as a result it is trivial to implement qualified type names (it is not a notation we want to use).

So we have two choices:

1. Change the syntax for session type sequencing,
2. or come up with a new, acceptable syntax for selection from modules

**Comment by jamescheney** [comment]
I remember we had a discussion about this clash a while back - I guess what we decided then was that we could use "." for module path steps in expressions and "." in session types no problem because they are different syntactic classes. Given that using sui generis syntax for module '.' would probably confuse everyone in the universe (unless we chose something horrible like C++'s "::") I guess it would be better to find a new symbol for session type "." that we can live with.

**Comment by dhil** [comment]
We are planning to upstream the new module system within the next few weeks, before we do that, we need to settle on a concrete syntax for member selection.

**Comment by jamescheney** [comment]
Recapping, the problem is that now modules will support qualified type names, not just qualified variable/component names, so that the session type syntax "M.x.M.y" is ambiguous.

One solution would be too keep "." for qualified name separator and change to another symbol (not already used in type syntax) for session type sequential composition.  Given that M.x is conventional in most ML-like functional languages, and few such languages have established syntax for session types, this seems preferable to me.  Some suggestions: ";", "..", ",".  (none of these cause conflicts if we allow them in session types, so it is just a matter of what is most readable).  

Another solution would be to use "." for session types and choose something else for qualified names.  I don't think we've heard any attractive suggestions for qualified name separators.

Am I missing anything?

**Comment by slindley** [comment]
The syntax `M.x.M.y` shouldn't be ambiguous. Dots only occur in session types after an output (`!A.S`) or an input (`?A.S`). The only ambiguity I see is if the carried type `A` is qualified. Does `!M.End.End` refer to `!(M.End) . End` or `!M . End.End` or the ill-formed `!M . End . End` or `!(M.End.End)` (writing `.` for module lookup and ` . ` for sequencing)?

I suspect the simplest solution is to insist that the carried type be either unqualified (e.g. `!Int.S`) or wrapped in parentheses (e.g. `!(M.A).S`).

**Comment by jamescheney** [comment]
OK.  I remember we had this discussion a year or more ago now, when @SimonJF  was working on the initial module system, which led to this workaround being put in place already (cf. parser.mly):

> /* Parenthesised dts disambiguate between sending qualified types and recursion variables.
>    e.g:
> 
>      S = !ModuleA.ModuleB.Type.S
>      should be written
>      S = !(ModuleA.ModuleB.Type).S
> 
>      Parenthesised versions take priority over non-parenthesised versions.
> */
> 

and I thought that the problem this issue is about was that this will no longer work for the new module system, but I'm now no longer sure why that is.

**Comment by SimonJF** [comment]
I agree with @slindley (and @jamescheney, whose comment just appeared). We had this discussion a long time ago and it was fixed (see the associated unit test in https://github.com/links-lang/links/blob/master/tests/modules/session-type.links).

This particular issue (#225) I believe stems merely from the fact that the return type of a function cannot contain a qualified variable, which should be a trivial parser fix -- however, it doesn't seem worth doing given that the new module system is incoming.

**Comment by jamescheney** [comment]
OK, so returning to @elordin's original example, this is a workaround:

```
# two.links
open One;
sig foo : (One.One) ~> (One.One)
fun foo (a) {
  a
}
```

and so is this:

```
# two.links
open One;

typename Three = (One.One);

sig foo : (One.One) ~> Three
fun foo (a) {
  a
}
```

but not this:


```
# two.links
open One;

typename Three = One.One;

sig foo : (One.One) ~> Three
fun foo (a) {
  a
}
```

That is, `X.y` in the RHS of a typename is also not allowed to be a qualified type.  

This appears to be because nonterminal `qualified_type_name` is only allowed inside a parenthesized (list of) types.  Allowing `qualified_type_name` as a `datatype` leads to the expected shift/reduce conflicts.

This seems awkward: I'd rather have to put parentheses (or some other delimiter/token) around session types (or use a different operation than ".") than around every non-parenthesized qualified type name.

**Comment by jamescheney** [comment]
Ah thanks @SimonJF.  I think the issue is that the way this was fixed had the unintended side effect of requiring parentheses around `qualified_type_name`s in all type expressions (including function return types, RHSs of `typename`, etc.), not just those occurring inside session types.  Fixing that should just be a matter of an hour or two of parser hacking that my brain is too tired to figure out just now.

**Comment by jamescheney** [comment]
So in particular it doesn't work to just add `qualified_type_name` as something that can appear on the RHS of an arrow, because this ambiguous:

```
? (asdf) ~> M.x . ghjk
```
My take on this is that requiring qualified type names to only appear immediately inside parentheses is far too restrictive, whereas I see no particularly good reason why a function type immediately inside a ? ... . should not need parentheses.  Instead, I think the types that are allowed inside ? ... . and ? ... . should be restricted way down to just base types (or whatever the most general type nonterminal is that cannot derive a qualified type name at the end).  More meditation on the grammar (preceded by food, sleep and coffee) needed.

**Comment by slindley** [comment]
Good point.

We could insist that the parentheses are always present, but that's a bit annoying for common cases such as writing `?Int.S` as `?(Int).S` and pretty horrible when we write `?().S` as `?(()).S`, though we do already write things like `(()) ~> A` for single argument functions whose argument has unit type.

A way of being more permissive is to allow carried types without parentheses providing they contain no qualified types anywhere as a subformula. I guess that may be slightly irritating to maintain as it might require duplicating every production in the datatype grammar - or is there some easy way of abstracting over such grammar extensions?

**Comment by jamescheney** [comment]
I'm not sure it's necessary to go that far, see #459...

**Comment by jstolarek** [comment]
I wonder whether using > instead of . for session types would be acceptable? (Though it looks James has alreday solved the problem.)
