### ISSUE TITLE
Redefining hd and pattern matching

### ISSUE THREAD

**Issue by fehrenbach** [links-lang/links#24]
This test fails:

```
Case patterns (with redefined hd)
{ fun hd(_) { 1 } switch (['a']) { case [y] -> y }}
stdout : 'a' : Char
```

My best guess: pattern matching desugars to calls to `hd` and `tl`, but is not hygienic.

**Comment by slindley** [comment]
You are correct.

**Comment by jamescheney** [comment]
Now that we have a module system, perhaps we should desugar to List.hd and List.tl, where List is a built-in module that provides the standard definitions of these operators.

**Comment by jamescheney** [comment]
Actually, this turns out to be trivial to fix, just by looking up the various functions in the initial environment rather than the current one passed in to the pattern compiler.  (Another clunkier fix that also worked was to have special versions of hd and tl that had names that are impossible to write in Links source code.)  See #843
