### ISSUE TITLE
Some impure programs never yield

### ISSUE THREAD

**Issue by dhil** [links-lang/links#253]
Spawning a divergent computation like `fun f() { f() } f()` causes the spawned process to never give up control (i.e. yielding), meaning that a process ID is never returned
```
links> spawn { fun f() { f() } f() };
<loops indefinitely>
```
Because the divergent computation is not pure one would expect it to (eventually) yield
```
links> fun f() { f() };
f = fun : () ~> _::Any
```
Running an effectful function like `random` during computation causes the right behaviour
```
links> spawn { fun f() { ignore(random()); f() } f() };
Pid Server (srvPid_0) : Process ({ wild|_ })
```
Note the signature of the function is the same as before
```
links> fun f() { ignore(random()); f() };
f = fun : () ~> _::Any
```

**Comment by slindley** [comment]
This behaviour has nothing to do with effects:

    ./links -e 'spawn { fun f() {var x = 42; f()} f() }'
    Pid Server (srvPid_0) : Process ({ wild|_::Any })

The issue is that `yield` is called for every `apply_cont` but not for every `apply`. If there is a plain `apply` then it will never yield. Given that `apply` sometimes calls `apply_cont`, simply wrapping a `yield` around calls to `apply` is not the correct fix. Still, it should not be hard to implement a correct fix.
