### ISSUE TITLE
Basicsettings.config_file_path not being used

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#266]
`config_file_path` in basicsettings.ml looks in the environment / `opam var` settings to find likely places to look for config file.  This is nice and means that (pre 0.7) no further configuration was needed if you did `opam install links`.

But now, `config_file_path` is not referenced from anywhere, particularly parseSettings.ml which just uses the command line option `config_file`, if any.  It looks like this might have changed when parseSettings.ml was split off.

This should be fixed and we should make a new version (0.7.1) with any other fixes we notice in the next few days.

**Comment by dhil** [comment]
I suppose the fix is to initialise `ParseSettings.config_file : string option ref = ref BasicSettings.config_file_path`?

On a related note, the whole handling of settings should be redesigned at some point. It is painfully side-effecty, and some parts of Links now depends on the order of those side-effects. I think this is worth its own issue.
