### ISSUE TITLE
Proposal: Allow command line arguments to be passed to programs

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#290]
I couldn't see a way of allowing Links programs to access command-line arguments.

Perhaps we should have one?

**Comment by fehrenbach** [comment]
Seems like that should be an easy exercise in using our shiny new OCaml FFI!
So new and shiny in fact that it doesn't even exist yet...

**Comment by dhil** [comment]
> I couldn't see a way of allowing Links programs to access command-line arguments.

I suppose you mean arguments supplied on the server side? In web mode you can access the environment via the `environment` function.

**Comment by dhil** [comment]
Following POSIX conventions for command line interfaces, here is what I have in mind:
```
./links --foo=bar --baz app.links -- a b c
```
The above starts Links with the option `foo` set to value `bar`, the flag `baz` toggled, and then compiles and runs `app.links`. The arguments `a`, `b`, and `c` are passed to `app.links` at runtime either via the `environment` function or some new primitive server-side function `getArgs`.

**Comment by SimonJF** [comment]
That sounds good. I was tempted by `environment` but I think this might get confusing, given that `environment` makes sense when generating a webpage (in order to process `POST` and `GET` arguments) whereas it may also be necessary to use command-line arguments. So I'd be more in favour of `getArgs`, along with your POSIX proposal.

**Comment by dhil** [comment]
> That sounds good. I was tempted by `environment` but I think this might get confusing [...]

Yes, that may be right. And somewhat cumbersome too as we would have to provide the arguments as a string rather than a list of strings, meaning the user would have to do some extra parsing. I will look into implementing another primitive function `getArgs : () ~> [String]` where the components of the result are the CLI arguments separated by spaces (we'll need to interpret `--foo="Some long string"` or standalone `"Some long string"` as a single contiguous argument).
