### ISSUE TITLE
OCaml 4.06 compatibility

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#299]
Work is needed to make Links (and dependent libraries) compatible with OCaml 4.06  @dhil can give more detailed examples.

**Comment by dhil** [comment]
OCaml 4.06 enforces the previously optional `-safe-string` option. Currently Links does not compile with `-safe-string` option. This problem ought to be fixed by #265. However, Links depends on `deriving` which in turn depends on `optcomp` which does not compile with `-safe-string` on. I two open PRs diml/optcomp#4 and ocsigen/deriving#40 which fixes their compatibility issues with 4.06.

**Comment by dhil** [comment]
My PR ocsigen/deriving#40 has been merged in. It might still take a little while for it to be included in a release.

**Comment by jamescheney** [comment]
Looks like this will be addressed by #332 once that is merged.

https://github.com/diml/optcomp/pull/4 indicates that the fix to optcomp is unlikely to be merged as it is not maintained, but suggests alternatives.

https://github.com/ocsigen/deriving/pull/40 seems to be merged but perhaps this is irrelevant now thanks to #332.

**Comment by frank-emrich** [comment]
Yes, #332 establishes full compability with 4.06.x.
Daniel intends to merge it tomorrow.

It seems like we are not using optcomp anymore? I don't see a dependency on it anywhere. Also, since we now have full support for ppx rewriters, we could easily use ppx_optcomp if we need optional compilation at a later point.

**Comment by dhil** [comment]
Yes, if I recall correctly we indirectly depend on optcomp via deriving. Once we have replaced deriving by ppx_deriving we should be compatible with the latest OCaml compiler again.
