### ISSUE TITLE
Inconsistent behaviour of Regex in REPL and Server

### ISSUE THREAD

**Issue by Corneliusbusch** [links-lang/links#345]
The behaviour of a function using regular expressions is inconsistent when used on the server and the Links REPL.

The following minimal example is supposed to print "False" to the Console after the button has been clicked as it checks whether the string of "-2" is a positive integer. 
However, in the Browser it prints true, whereas when run in the Links REPL, the function correctly rejects "-2" as a positive integer. 

The minimal example: 
```
sig isPosInt: (String) -> Bool
fun isPosInt(n){
    (n =~ /^[0-9]+$/)
}

sig main_page : (_) ~> Page
fun main_page(_) {
    page
    <html>
        <div id="content">
           <button l:onclick="{if( isPosInt("-2") ) print("True") else print("False") }">
                 Is -2 a positive Integer? 
           </button>
        </div>
    </html>
}

sig main: () ~> ()
fun main() {
    addRoute("/", main_page);
    servePages()
}

main()
```

When called in the Links REPL, the correct result is returned. 
```
links> sig isPosInt: (String) -> Bool
...... fun isPosInt(n){
......     (n =~ /^[0-9]+$/)
...... };
isPosInt = fun : (String) -> Bool
links> isPosInt("-2");
false : Bool
```

**Comment by jamescheney** [comment]
This seems likely to be due to differences between client (JS) and server (OCaml/PCRE) implementations of regexes.  Are you sure the regex operation is happening on the server and not the client?  What happens if you put the "server" keyword in "isPosInt"?  Not that you necessarily want to be calling the server just to do regex matching.

**Comment by Corneliusbusch** [comment]
If I add the "server" keyword in "isPosInt", it evaluates correctly and prints "False". However, if I add the "client" keyword, it prints "True". So, I guess, the inconsistency is between REPL and client?

**Comment by dhil** [comment]
The compilation of regular expressions to the client is completely broken. The regex `/^2$/` seemingly gets compiled as a list object 
```
{"regex": 
    {"_label": "Seq", 
     "_value": {"_head": 
                       {"_label": "StartAnchor", "_value": {}}, 
                     "_tail": 
                       {"_head": 
                          {"_label": "Simply", "_value": "2"}, 
                        "_tail": 
                            {"_head": 
                                {"_label": "EndAnchor", "_value": {}}, 
                             "_tail": null}}}}}}
```
The whole object is being fed into `_tilde` as `regex`
```
function _tilde(s, regex) {
  var r = Regex.compile(regex);
  return (new RegExp(r)).test(s); // makes garbage
}
```
According to the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/compile) the method `compile` takes two arguments `(pattern, flags)` where `pattern` is a textual representation of the regular expression. Since JavaScript is happy to fail silently, it emits the string regular expression for any ill-formed input to `compile`.

Furthermore, documentation page says that `Regex` has been deprecated. Thus we will have to find another way to implement regular expressions on the client, if we wish to continue supporting it as a feature.
