### ISSUE TITLE
No tame expressions allowed at toplevel

### ISSUE THREAD

**Issue by frank-emrich** [links-lang/links#364]
Consider the following code defining a tame function and calling it at the toplevel:
```
sig f : (Int) {}-> Int
fun f(x) {x}
links> f(2);
```
This yields the following error:
```
Type error: The function
    `f'
has type
    `(Int) {}-> Int'
while the arguments passed to it have types
    `Int'
and the currently allowed effects are
    `wild'
In expression: f(2).
```

**Comment by dhil** [comment]
To be more specific, this only happens when the expression is a function application, and the function being applied is typable as pure, i.e. its effect row is empty and closed.

I suppose this is an unintended side-effect of @slindley's fix to restrict toplevel functions to have an effect type compatible with `{wild}`.

**Comment by jamescheney** [comment]
If we are not doing #365, does that imply we should close this?  Or are people still unhappy about this but #365 isn't the right way to address it?

**Comment by dhil** [comment]
Good catch! #365 is a fine solution in my opinion. However, I suppose we can close this now.
