### ISSUE TITLE
Instantiation arity mismatch

### ISSUE THREAD

**Issue by dhil** [links-lang/links#366]
The following program causes an `Instantiate.ArityMismatch` error
```
fun f(p, q) {
  switch (0) {
    case 0 -> p(q)
    case n -> f(p, fun(_) { true })
  }
}
```
The error message is
```
# Type variables (total 0)


# Type arguments (total 2)
1. `Type (`MetaTypeVar (...))
2. `Row (({}, ..., false))
Arity mismatch in type application
Expression: `TAppl (((`Var ("q"), ...),
         [`Type (`MetaTypeVar (...)); `Row (({}, ..., false))]))
Type: (_) -> Bool

```

The error does not happen when using `if-then-else` rather than the `switch`, e.g.
```
fun f(p, q) {
  if (true) {
    p(q)
  } else {
    f(p, fun(_) { true })
  }
}
```

**Comment by jamescheney** [comment]
The following simpler example yields a similar error message:
```
fun f(q) {
  switch (true) {
    case true -> q
    case false -> f(fun (x) {x})
  }
}
```

However, rearranging the cases yields success:
```
fun f(q) {
  switch (true) {
    case false -> f(fun (x) {x})
    case true -> q
  }
}
```
with inferred type 
```
((a::Any) -b-> a::Any) ~> (a::Any) -b-> a::Any
```
This suggests that the type information from the first and second cases is being combined in an order-sensitive way, which should ideally not be the case.  Perhaps also this is related to #446, #534 since if the `fun` subexpression is properly generalized then the type of `f` should quantify over `a`,`b` in its argument?

The following example also typechecks:
```
fun f(p, q) {
  switch (0) {
    case 1 -> f(p, fun(_) { true })
    case 2 -> f(p, fun(_) { false })
    case 3 -> p(q)
    case 4 -> p(q)
  }
}
```
but none of the other possible interleavings of the cases I've tried (i.e. with a `p(q)` before `f(p,...)`) works.
