### ISSUE TITLE
Running test suite is slow due to repetitive re-processing of prelude

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#373]
As @slindley  pointed out, since we removed caching (yay) running lots of tests takes longer due to re-processing/checking of the prelude.   We could maybe reinstate a simpler form of caching for prelude, or even explicitly serialize/deserialize the IR on a module by module level (and typecheck on deseriazation?!) to improve performance.

**Comment by jamescheney** [comment]
We haven't done this, but the parallelization of the test suite #556 seems to help a lot; I think the second approach above (i.e. "separate compilation" to IR + factoring Links into a cleanly separated frontend vs backend) would be sensible longer term but that seems like a separate issue (or project).

**Comment by frank-emrich** [comment]
Indeed, generalizing the support for "pre-compiled modules" is something me and Daniel have in mind longer term. This would require us to be able to store a semi-compiled version of a module, probably just the marshaled IR code + the module type. It would essentially mean that if we see an `import`, we would check if we have an up-to-date compiled version, and only process the source otherwise. Of course, this is essentially just a generalization of what you implemented for the prelude caching, but hopefully in a less ad-hoc manner.

If we are interested in decreasing the run-time of the CI runs (as opposed to running the tests locally), we could re-visit the idea of using a docker image that contains a pre-compiled version of a recent OCaml compiler. Currently, a CI run takes 14 minutes, half of which is spent building OCaml and Links' dependencies. Using the docker image could greatly reduce those first 7 minutes.

**Comment by jamescheney** [comment]
> hopefully in a less ad-hoc manner.

That shouldn't be hard :)

**Comment by jamescheney** [comment]
Since #556, this seems no longer to be an issue.  Longer-term, I think we want to move towards a separate compilation approach which would also help with this.  But that's a project, not an issue :) so I think we can close this now.
