### ISSUE TITLE
Move to OPAM 2.0

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#410]
With the release of OPAM 2.0, we will need to update the format of our OPAM files before we do the next release.

**Comment by jamescheney** [comment]
just to further +1 this, at the moment Links depends transitively on a ssl package that doesn't install correctly on MacOS and the fix is an OPAM 2.0 package.

**Comment by slindley** [comment]
I think MacOS is a red herring. If I understand correctly, that version of that package no longer installs anywhere because the package maintainer violated the basic assumptions of OPAM by updating a URL in an already released package to point to a non-existent file - @SimonJF can tell you all of the gory details.

**Comment by jamescheney** [comment]
Ugh. Upgrading to opam 2 fixed the problem, (modulo blowing away opam 1.2 cruft) anyway.

**Comment by SimonJF** [comment]
The package owner has re-uploaded `ssl` at the previous URL, so we shouldn't have any more issues with it thankfully.

Nonetheless, OPAM 2.0 compatibility is a priority.

**Comment by jstolarek** [comment]
It makes me sad that due to a bug OPAM 2.0 does not work on a setup where `~/.opam` is a symlink to a directory on a partition with more disk space:

https://github.com/ocaml/opam/issues/3622

Am I the only one affected?

**Comment by frank-emrich** [comment]
This should be fixed by #416, but @SimonJF would have to test at some point if we can actually build releases with opam2. I'm closing this for now.
