### ISSUE TITLE
Menhir parse errors

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#428]
I've just installed the latest version of Links, and I'm getting a problem with parse errors.

```
fun main() {
  var (x, y) = (1, 2)
  print(intToString(x))
}

main()
```

There is a parse error since we're missing a semicolon after the pair deconstruction. However, when running this through Links, I get the following:

```
[simon@guadeloupe scraps]$ links test.links 
*** Error: Links_core__Parser.MenhirBasics.Error
```

I'd expect some position information. Is this a misconfiguration on my part, or an issue introduced by #425?

(Apologies for raising this just after the merge -- been swamped with thesis writing up until now, so didn't get a chance to try out the branch).

**Comment by jstolarek** [comment]
That's totally my fault. Sorry.

There are two ways to fix this. One is to more-or-less restore previous error messages that just say "Parse error at line X". This should be simple. However, this method of reporting errors in Menhir is considered deprecated and it might be removed in the future. In its place Menhir offers a new method of handling parse errors. It allows to provide more accurate error messages, e.g. "A semicolon was expected after a binding", but it requires that we actually write messages for all possible error states that can occur in the parser. Menhir provides tools to simplify the task, e.g. it can figure out all possible states that lead to an error and generate a stub configuration file. However, the whole task looks challenging. I just checked and there are 632 possible error states in Links - so possibly 632 error messages. Secondly, this file needs to be maintained as grammar changes. Again, there are tools to help in that, but it still has to be done. Thirdly, figuring out what the error messages should say looks non-trivial - Menhir provides examples of what might cause the error, but there are caveats. 

So I'll fix bug by trying to restore the previous behaviour as much as possible. I'll leave the implementation of more advanced parse error handling as an exercise to the reader :-)

**Comment by SimonJF** [comment]
Not at all -- thanks for looking into it and for your work updating the parser! 

Just the position information would be great for now; everything else seems non-trivial (and would likely need to be redone after #426).

**Comment by jamescheney** [comment]
By default Menhir should work more or less like ocamlyacc so it should just be a matter of catching the parse error exception which (hopefully) has the position embedded in it.

Menhir also supports nicer error messages based on a classic TOPLAS paper, as blogged here:

http://semantic-domain.blogspot.com/2015/11/error-handling-in-menhir.html

The basic idea is you should be able to write a declarative spec somewhere that says:

```
fun main() {
  var (x, y) = (1, 2)
  print(intToString(x))
}

main()
--should yield an error message like-->
"Missing semicolon after var declaration"
```

and you maintain that instead of the 632 error messages.  You just need to write a new error message every time you get a bad or default one.

**Comment by jamescheney** [comment]
Though, hmm.  Maybe the 632 possible error states are what Pottier's paper provides... might be interesting to look at previous examples.

**Comment by jstolarek** [comment]
> Menhir also supports nicer error messages based on a classic TOPLAS paper

Yes, this is exactly that second way of handling error messages. And I'm not saying we should have 632 *distinct* error messages. But this is how many possible parse errors there are in our grammar.

Anyway, the fix for this should be just to catch a different exception in `parse.ml`. I just need to look at Menhir source code, because the documentation is silent on this.

**Comment by SimonJF** [comment]
Thanks!

**Comment by jstolarek** [comment]
That was a one-liner.
