### ISSUE TITLE
Some 2000 warnings during build

### ISSUE THREAD

**Issue by dhil** [links-lang/links#430]
Commit [`bb3318cccb9cf5e782e43d8a556037e7eff3d4bb`](https://github.com/links-lang/links/commit/f8dbc830f31ef7f8fec891b0afe4d24030709080]) appears to have introduced loads of warnings when building using `make nc`. I get about 2000 warnings of the kind
```
File "jsonparse.ml", line 645, characters 12-719:
Warning 9: the following labels are not bound in this record pattern:
state
```
Compiler: OCaml 4.06.1.
Menhir version: 20181006

**Comment by dhil** [comment]
The warnings get swallowed somehow when building using the `release` profile (`make build-release-all`) which would explain how the commit passed the CI as it is running using that profile.

**Comment by jstolarek** [comment]
@dhil, what happens if you upgrade Menhir? I tried to reproduce this with menhir version 20181113 and Ocaml versions 4.06.1 and 4.07.1 and both builds are warning-free on my machine.

Also, which commit do you mean? Link description says  bb3318cccb9cf5e782e43d8a556037e7eff3d4bb but link points to f8dbc830f31ef7f8fec891b0afe4d24030709080. I take it that you mean the latter. (BTW you can just paste commit hash into the edit box and github will convert it into a link to relevant commit.)

**Comment by dhil** [comment]
I just did `opam update && opam upgrade`, now the warnings are gone. I can no longer reproduce. Strange!
