### ISSUE TITLE
Whitespace rule checker checks binary files

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#464]
The whitespace rule checker currently runs the following command:

```
find "$dir"  -type f -not -name "*.pdf" -exec egrep -l " +$" {} \;
```
meaning that it is run on every file that isn't a PDF. Adding a few PNGs seemed to cause the check to fail.

I wonder whether it might be better to go for a "check these file types" approach, rather than a "don't check these file types" approach, allowing us to restrict attention to only files which are textual. For example, I would consider the following list:

- ml
- mli
- mly
- mll
- py
- pl
- html
- js
- txt
- md
- links
- css
- sh

**Comment by dhil** [comment]
@SimonJF yes, it is obviously correct to whitelist rather than blacklist. You also need to consider "dune", "dune-project", "opam", "el", and "vim" files. We should possibly omit "INSTALL", "README.md", "ACKNOWLEDGEMENTS", and "LICENSE.md" as the Markdown format has syntactic relevant trailing whitespace.
