### ISSUE TITLE
Documentation in `doc/` directory is out of date

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#474]
A quick glimpse at grammar description in `grammar.tex` and language tutorial `quick-help.pod` in the `doc/` directory reveals these documents are out of date. It would be nice to have some up-to-date description of Links - but just one, not two. What format should we use? Having grammar in TeX will allow easier reuse in papers. If not TeX then I suggest moving from POD to Markdown, which for example could be placed in a wiki. Or maybe som other format, like [Ott](https://www.cl.cam.ac.uk/~pes20/ott/) (again, easier reuse in papers)?

Probably worth discussing during the next Links dev meeting.

**Comment by jamescheney** [comment]
This issue is a little too open-ended - it's really a project IMO.

As mentioned in the Skye project meeting yesterday, I think we should make a simple ReadTheDocs-style "documentation manager" web app using Links, and use it to document Links.  (preferably using a standard markup dialect so that we can sync with standard wiki pages like the ones in the GitHub wiki).  

One concrete things we should definitely fix asap, however, is the usage/installation instructions at the end of quick-help.pod.  They still refer to running Links in CGI mode which is no longer possible.  There should also be better signposting of the existing getting-started documentation in the wiki.  I was talking to someone about Links today and `doc/` was where they were looking for information about how to get started!

**Comment by SimonJF** [comment]
This is beginning to be fixed in #737 .

**Comment by jamescheney** [comment]
Now that #737 is merged, can we close this and create new specific issues in the "Documentation, examples and testing" project?

**Comment by jstolarek** [comment]
Yes.
