### ISSUE TITLE
Cannot parse qualified parameterised typenames

### ISSUE THREAD

**Issue by dhil** [links-lang/links#483]
On the master branch it seems that qualified parameterised type names cannot be parsed.
foo.links
```
typename T(a) = Bool;
typename S = Bool;
```
bar.links
```
open Foo;
sig f : (Foo.T(Int)) -> Foo.T(Int)
fun f(x) { not(x) }
```
```
$ links -m --path=. bar.links
*** Parse error: bar.links:2

  sig f : (Foo.T(Int)) -> Foo.T(Int)
                   ^
```

However, if the type name has no parameters, then it parses just fine.
baz.links
```
open Foo;
sig g : (Foo.S) -> Foo.S
fun g(x) { not(x) }
```
```
$ links -m --path=. baz.links
() : ()
```

I suppose #459 may not have accounted for qualified parameterised type names.

**Comment by jamescheney** [comment]
This doesn't work either:

```
open Foo;
typename U = (Foo.T(Int));
sig f : (U) -> U
fun f(x) { not(x) }
```

I don't think this has anything directly to do with #459 since that was just about reducing the need to explicitly parenthesize things, the fix didn't (or at least shouldn't) add or remove any ability to create particular abstract syntax trees.  The above examples seem to indicate that there is currently no way to parse the type application `Foo.T(Int)` at all, so this probably needs to be added to the grammar.

for example by changing one of the following lines in parsem.mly:

```
| qualified_type_name { `QualifiedTypeApplication ($1, []) }
```

```
| CONSTRUCTOR LPAREN type_arg_list RPAREN                      { `TypeApplication ($1, $3) }
```

I might take a shot at this in a minute...

**Comment by dhil** [comment]
> I don't think this has anything directly to do with #459 since that was just about reducing the need to explicitly parenthesize things [...]

In other words, it may never have worked. I discovered this after rebasing the `proper-modules` branch on top of master, as some simple tests were failing.
