### ISSUE TITLE
Investigate `labels` argument in `DBInsert`

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#488]
`labels` argument to `DBInsert` phrasenode is ignored during desugaring (`DBInsert`s are discarded at this stage). Is it used anywhere else? If not, can it be safely removed?

**Comment by jamescheney** [comment]
In SQl, insert statements separate the field labels from the values:

```
INSERT INTO tbl_name (a,b,c) VALUES(1,2,3),(4,5,6),(7,8,9);
```
However, in Links we (redundantly) keep the SQL-like label vector but require the inserted values to be records anyway, since to do otherwise (using tuples/positional alignment) seems silly in a compositional language with row types:
```
insert tbl_name (a,b,c) values [(a=1,b=2,c=3),(a=4,b=5,c=6),(a=7,b=8,c=9)];
```
(We are however allowed to leave out `(a,b,c)` if the inserted expression is a singleton list containing a record value.)

I believe that how this works in Links is that the labels are used in typechecking to determine the inserted field names, and this is checked against the actual record types of the inserted records during typechecking.  After that point, the field names can be extracted from the inserted record(s).  (If there aren't any records to insert, then the type is ambiguous but there is nothing to do anyway).

I'm not completely sure we actually need the field names in insert statements.  In `typeSugar` we currently only use `labels` to create a record type with the given field labels and new type variables, and unify it right away with the already-inferred type of the records to be inserted.

Perhaps removing the labels from `insert` statements could allow more flexibility (e.g. writing functions that are row-polymorphic over the types if records they insert) at the cost of potentially disorienting people familiar with SQL inserts.  Or we could make it optional, and allow more flexible polymorphic behavior for those willing to free their minds from language design decisions made 40 years ago.

**Comment by jstolarek** [comment]
>  In `typeSugar` we currently only use labels to create a record type with the given field labels and new type variables, and unify it right away with the already-inferred type of the records to be inserted.

So we do use these labels in some way. I'll close this ticket and leave the refactoring ideas as an exercise to the reader.
