### ISSUE TITLE
Value restriction and effect signatures

### ISSUE THREAD

**Issue by dhil** [links-lang/links#53]
The type checker rejects the following program

```
links> sig foo : () {Bar:a|_}-> a
...... fun foo() { var x = do Bar; x };
<stdin>:2: Type error: Because of the value restriction there can be no
free rigid type variables at an ungeneralisable binding site,
but the type `_' has free rigid type variables.
In expression: var x = do Bar;.
```

Even though the type checker **infers** that type

```
links> fun foo() { var x = do Bar; x };
foo = fun : () {Bar:a|_}-> a
```

If the type variable `a` appears first time outside of the effect row then it type checks:

```
links> sig foo : (a) {Bar:a|_}-> a
...... fun foo(y) { var x = do Bar; x };
foo = fun : (a) {Bar:a|_}-> a
```

But only if the dummy variable (`y`) is not `any`, i.e.

```
links> sig foo : (a) {Bar:a|_}-> a
...... fun foo(_) { var x = do Bar; x };
<stdin>:2: Type error: Because of the value restriction there can be no
free rigid type variables at an ungeneralisable binding site,
but the type `_' has free rigid type variables.
In expression: var x = do Bar;.
```

**Comment by dhil** [comment]
Perhaps unsurprising the example type checks when using flexible type variables
```
links> sig foo : () {Bar:%a|_}-> %a
...... fun foo() { var x = do Bar; x };
foo = fun : () {Bar:a|_}-> a
```

**Comment by dhil** [comment]
The issue is reproducible in the sessions branch using the built-in _hear_ effect
```
links> sig foo : () {:a|_}~> a 
...... fun foo() { var x = recv(); x };
<stdin>:2: Type error: ...
```

**Comment by slindley** [comment]
The issue only occurs for non-recursive functions. The problem is that it is sometime necessary to propagate type information from the type signature to the body of the function (e.g. when we make use of recursive types which cannot be inferred), and yet for a non-recursive function it is unsound to add the function itself to the environment so type variables in the function signature do not occur anywhere in the environment. An easy hack is to add a fresh dummy variable with the type annotation to the environment.
