### ISSUE TITLE
`int_of_string` error when handling null integers in LINQ queries

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#546]
I'm a bit perplexed as to how `null` integers are handled in the database. Suppose we have:

```
fun getDummyData() {
  var tbl = table "dummy" with (foo: Int) from database "test";
  query {
    for (i <-- tbl)
      [(id=i.foo)]
  }
}

fun main() {
  var xs = getDummyData();
  iter(fun (x) { debug(intToString(x.id)) }, xs);
}
```
where column `foo` is nullable and the table contains a null integer value, then we get an `int_of_string` error. This seems to happen with both flat and nested queries.

That said, I'm not sure what sensible behaviour would even be for this case.

**Comment by jamescheney** [comment]
Ah, that's what I thought might be the issue.  Links currently completely punts on how to handle `null`s.  I would like to do better, for example by allowing Option types in table definitions/query results (so that whenever `ty` is a base type, so is `Option(ty)`) and treating `null` values in query results as `None`.  However, we currently have no metatheory for this.  This is something I was thinking of doing next building on Wilmer's work on formalizing SQL semantics in the presence of nulls.  So it is grimly satisfying to know that this is actually something we run into when trying to work with a real DB.

What would be a minimal workaround to get this to work in your setting until we do have a better story for nulls?

**Comment by SimonJF** [comment]
A minimal workaround would be to have, say, -1 as a default value. Most of the null tables end up being foreign key references so are non-negative. This would definitely be a hack though.

**Comment by jamescheney** [comment]
That's what I was thinking too but hesitated to suggest (since -1 is a perfectly legitimate integer).    

Another issue is strings; I think a null value in a string field is indistinguishable from the string "NULL" and not sure how to get around that.  Life is much easier without nulls!

One epsilon-more-principled possibility is that we could add database-able builtins called things like "isNull : (a) -> Bool" that gets mapped to the "IS NULL" test in SQL.  (Outside of the DB, this would just be the constant false function.) Then we could write queries that test for null-ness of certain fields and replace their values with appropriate defaults rather than having the default value of -1 hard-wired in Links somewhere.  This would also avoid the ambiguity between the `null` and literal `"NULL"` strings which otherwise I'm not sure how to avoid.  

However, there are other null and 3-valued logic related issues that this would not handle, and in particular I have no strong reason to believe that all of the rewrites we use to normalize Links queries are valid in the presence of nulls, in particular the one that goes:
```
if M then N else P --> if M then N else [] ++ if not(M) then P else []
```
since P or not P is not a tautology in 3-valued logic.

So there may be other subtle bugs because of nulls.

**Comment by SimonJF** [comment]
> That's what I was thinking too but hesitated to suggest (since -1 is a perfectly legitimate integer).
Yes, absolutely -- it would definitely be a hack and rather unprincipled. It's not a complete blocker: there are a few data pages which don't work, but on the whole it's OK.

> One epsilon-more-principled possibility is that we could add database-able builtins called things like "isNull : (a) -> Bool" that gets mapped to the "IS NULL" test in SQL.

That's a *lot* more principled. I like that solution a lot. I'm not entirely sure of the intricacies of actually avoiding a null integer dereference here though. One potential solution is to return the default value of -1 to avoid the dereference, and then allow the user to use the `isNull` primitive to determine whether the integer is _really_ -1, or rather is null.

> However, there are other null and 3-valued logic related issues that this would not handle
Ooft. What a headache. That said, it's interesting that there's (potentially rather impactful) research to be done there.

**Comment by jamescheney** [comment]
So the idea is to use the `... IS NULL` test *inside the generated SQL query* which is a way to distinguish between null values and ordinary ones on the database side -- not generate default values and try to untangle them in Links.  This combined with if-then-else (i.e. SQL "CASE") should make it possible to do e.g.

```
query {
  for (x <-- t)
  [(a = x.a, b = if (isNull (x.b)) { -1} else {x.b})])]
}
```

which should generate some SQL along the lines of 
```
SELECT x.a AS a, (CASE  WHEN x.b IS NULL THEN -1 ELSE x.b) as b
FROM t x
```

We could also package up the null/option handling in a function:
```
fun getUnlessNull(x: a, default: a) {
  if (isNull(x)) {default} {x}
}
```
of course, this is more or less just committing the same sin of implicit null values in Links that SQL did, and would still let you have a delightful run-time error if you aren't aware that `b` is nullable and don't do the check.  Just another few dollars into Hoare's billion-dollar mistake jar.

**Comment by jamescheney** [comment]
So, this is worked around by #643.  I think we should close this issue and make a new one about possible designs for handling nulls (of all types).

**Comment by SimonJF** [comment]
Agreed.
