### ISSUE TITLE
Any way to specify column names, where column name is a keyword?

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#557]
I'm currently using a database which has `prefix` as a column name, which is reserved. A constraint is that I don't really want to change the database.

From what I've seen, record fields map directly onto column names, and I can't see any way to use reserved words.

Is there any mechanism for specifying column names as strings, to avoid clashes with keywords? I thought it might have been `tablekeys`, but it doesn't seem to be (and I don't really understand what `tablekeys` does, either).

**Comment by jamescheney** [comment]
Argh, yes, this is a limitation I think.  Probably the right thing to do is to add indirection so that the Links record name doesn't have to be the same as the SQL column name.  (That would have been a way around #27 also).

Perhaps an alternative could be to allow single-quoted "string literals" as labels, i.e. for, say, 'prefix' or 'select' to be a valid Links record label as well as a valid SQL field name.

A shorter-term workaround could be to create a (very simple) view of the table in question (using SQL `CREATE VIEW`) that redefines the column name `prefix` as something else and keeps everything else the same.  This would technically be changing the database, but not in an important way; also the view is simple enough that it ought to be updatable in plain SQL, if we need to update it.

**Comment by SimonJF** [comment]
Thanks for the clarification. I don't think it should be too difficult to add, if we come up with a syntax. Something like:

```
table "database" with (database_id: Int, name: String, url: String, specialist: Bool, db_prefix: String)
  columns ["database_id", "name", "url", "specialist", "prefix"] from db;
```
where mismatching column / record counts is a type error.

**Comment by yallop** [comment]
In some SQL implementations column names are are case-insensitive.  Does that help as a workaround here (i.e. can you use `pReFiX` as a record field to access the `prefix` column)?

**Comment by jamescheney** [comment]
I think rows appearing in tables are allowed to be open, so using positional alignment to match up the field names and SQL labels won't be stable.  Plus it would be nice not to have to repeat the field names that are already legal SQL. Luckily, row types to the rescue.  I think something like 

```
table "database" with (database_id: Int, name: String, url: String, specialist: Bool, db_prefix: String)
  aliases (db_prefix:"prefix") from db;
```
would be more likely to work, we can just specify a subset of Links record field names and give their SQL meanings as necessary instead of having to repeat all of them.  We already do something similar to specify field accessibility (read/write or readonly).  The `aliases` row could then also be open so that tables could be constructed using row variables even if some abstracted fields are aliased.

**Comment by SimonJF** [comment]
@yallop : Good thought! Alas, doesn't seem to be insensitive with Postgres.

@jamescheney : Good point, you're absolutely right. That design seems nice to me.

**Comment by fehrenbach** [comment]
"prefix" is reserved in Links, but not in SQL, right?
The workaround for this direction is using quoted strings as record fields in Links: `table "tablename" with ("prefix": Int)` should be just fine. (Works with columns called "table" which appears in where-provenance occasionally.)

The other direction: reserved/special in SQL but not in Links should IMO be dealt with by the query code, if it's not already.

**Comment by jamescheney** [comment]
Ah, I had a vague feeling that we were already allowing quoting of string literals as labels but had forgotten.  Might be worth updating the documentation, which implies that `("abcd"=123)` is illegal, whereas Links is perfectly happy with it.

Thanks @fehrenbach for stopping us implementing a superfluous workaround!

**Comment by jamescheney** [comment]
@simonJF if this works for you 
```
table "database" with (database_id: Int, name: String, url: String, specialist: Bool, "prefix": String)
```
we can just close.  If not let us know why it doesn't help.

**Comment by SimonJF** [comment]
Works a charm -- thanks @fehrenbach. I had no idea we could do that!

Thanks everyone for your suggestions. We can close this now.
