### ISSUE TITLE
Application server

### ISSUE THREAD

**Issue by jgbm** [links-lang/links#56]

**Comment by jamescheney** [comment]
Is this closed by #101?  I think it should be closed, and if there are known issues still to be dealt with then they should be created as new issues.

**Comment by slindley** [comment]
It isn't closed but I see no reason to waste time creating any new issues just now. I merged it because it pretty much works and doesn't break any of the existing tests or examples. Running in CGI mode works just as it did before. Once I have rebuilt more of the examples using app server mode and done a bit more testing then I will close it.

**Comment by jamescheney** [comment]
OK, thanks.  I asked because the 7397 bug is described only in #101 so we should keep a placeholder somewhere of its existence.

**Comment by slindley** [comment]
Ah... yes. That could be registered as an issue. But that has nothing whatsoever to do with #101 (except that the app server made things fast enough that I could test numbers that big with the progress bar example).

**Comment by jstolarek** [comment]
@slindley, what remains to be done for this ticket to be close? Can we have a TODO list in the first post perhaps?

**Comment by slindley** [comment]
Nothing. There are issues with the application server, but they're being dealt with separately.
