### ISSUE TITLE
How to print type names from opened modules?

### ISSUE THREAD

**Issue by frank-emrich** [links-lang/links#595]
Consider the following program:

```
module A {
  typename Foo = Int;
}

open A;
sig x : Foo
var x = 3;
x
```

We currently have a test case assuming that the result of this program should be printed as `3 : A.Foo`, meaning that we fully expand the name to its original location. That sounds reasonable, but doing so systematically would mean that printing all types from the prelude would be prefixed similarly. I would prefer seeing `Maybe` as a type name rather than `Prelude.Maybe`. Note that this only affects the printing of types, not the types that the user writes (as seen in the example program, we can write `Foo` after opening `A`. Similarly, the prelude is implicitly opened in each program).

Here are a few solutions:
1. Do not expand the type names, meaning that the result of the program above would be   `3 : Foo` instead of  `3 : A.Foo`.
2. Expand all type names, meaing that we would see  `3 : A.Foo`, but also `Prelude.Mayne`.
3. Expand user-written type names (e.g., do  `3 : A.Foo`) but allow some minor inconsistency by suppressing `Lib` and `Prelude` when printing the type names from those modules.

**Comment by dhil** [comment]
Why would we ever print `3 : A.Foo`? The type `Int` is not shadowed in your example program. Did you mean to type `sig x : Foo`?

I think the right approach is to always print the qualified name relative to the context, possibly including its equation(s). The `open` construct is just syntactic sugar for writing fully qualified names yourself. For example assuming `sig x : Foo`, then the type of `x` should be printed as `A.Foo`. 

As another example consider the following erroneous program
```
module B {
  typename T = Int;
  sig f : (T) -> T
  fun f(x) { x +. 1.0 }
}
```
I would expect the type error to talk about `T = Int` be compatible with type `Float` rather than `B.T = Int`, as the latter is not meaningful in the (local) context (that is assuming our modules aren't recursive).

**Comment by frank-emrich** [comment]
> Did you mean to type sig x : Foo?
Indeed. I updated the description.

> I think the right approach is to always print the qualified name relative to the context, possibly including its equation(s).

That sounds reasonable, but raises the issue mentioned in my third solution: Should we exclude `Lib` and `Prelude` from this rule?
