### ISSUE TITLE
HTML attributes broken in client code?

### ISSUE THREAD

**Issue by ezrakilty** [links-lang/links#670]
The following program doesn't seem to behave correctly. In the initial (server-side) rendering, it works as expected, with the text in red, but after clicking, it becomes black. It seems that the JS code that evaluates attribute list doesn't actually know about the list data structure The attributes are replaced with _head="[Object object]" _tail="[Object object]", which the browser doesn't know what to do with.

```
fun core() {
  <div id="me" l:onclick="{replaceNode(core(), getNodeById("me"))}" { [("style", "color:#ff8080")] }>
  Test
  </div>
}

fun thepage() {
  page
    <html>
    { core() }
    </html>
}

fun main() {
  addRoute("/", fun(_) {thepage()});
  servePages()
}

main()

```

**Comment by dhil** [comment]
Interesting. It looks like the continuation somehow gets attached to the new node. This is definitely a bug.

I think since the introduction of the app-server the special `l` attributes have been broken. For example, `l:onload` doesn't work because the app-server consumes the on load event. Similarly, I think the various `l:onkey*` are broken.

**Comment by SimonJF** [comment]
We agreed in the meeting that I would look and at least triage this before 0.9.
