### ISSUE TITLE
IR typing is unaware of unsafe signatures

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#691]
code:
```
unsafe sig map : ((a) -b-> c, [a]) -b-> [c]
fun map(f, l) {
  switch (l) {
    case []     -> []
    case hd::tl -> f(hd) :: map(f,tl)
  }
}
```
error:
```
***: IR Type Error: Type mismatch:
 Expected:
  `Function ((`Record (({1 => `Present (`MetaTypeVar (Point @ 0x7f707d60bd90 `Var (
                                                    (350,
                                                     (CommonTypes.Linearity.Unl,
                                                      CommonTypes.Restriction.Any),
                                                     `Rigid))));
                       },
                      Point @ 0x7f707dca2cc8 `Closed, false)),
            ({wild => `Present (`Record (({}, Point @ 0x7f707dca2cc8 `Closed,
                                          false)));
              },
             Point @ 0x7f707d60bf68 `Var ((351,
                                           (CommonTypes.Linearity.Unl,
                                            CommonTypes.Restriction.Any),
                                           `Rigid)),
             false),
            `MetaTypeVar (Point @ 0x7f707d60bff8 `Var ((352,
                                                        (CommonTypes.Linearity.Unl,
                                                         CommonTypes.Restriction.Any),
                                                        `Rigid)))))
 Actual:
  `Function ((`Record (({1 => `Present (`MetaTypeVar (Point @ 0x7f707d5b2400 `Var (
                                                    (350,
                                                     (CommonTypes.Linearity.Unl,
                                                      CommonTypes.Restriction.Any),
                                                     `Rigid))));
                       },
                      Point @ 0x7f707dca2cc8 `Closed, false)),
            ({},
             Point @ 0x7f707d5b2278 `Var ((351,
                                           (CommonTypes.Linearity.Unl,
                                            CommonTypes.Restriction.Any),
                                           `Rigid)),
             false),
            `MetaTypeVar (Point @ 0x7f707d5b22e8 `Var ((352,
                                                        (CommonTypes.Linearity.Unl,
                                                         CommonTypes.Restriction.Any),
                                                        `Rigid)))))
occurring in IR binding:
(Ir.Let (
   (230,
    (`Function ((`Record (({1 => `Present (`MetaTypeVar (Point @ 0x7f707d60bd90 `Var (
                                                         (350,
                                                          (CommonTypes.Linearity.Unl,
                                                           CommonTypes.Restriction.Any),
                                                          `Rigid))));
                            },
                           Point @ 0x7f707dca2cc8 `Closed, false)),
                 ({wild => `Present (`Record (({},
                                               Point @ 0x7f707dca2cc8 `Closed,
                                               false)));
                   },
                  Point @ 0x7f707d60bf68 `Var ((351,
                                                (CommonTypes.Linearity.Unl,
                                                 CommonTypes.Restriction.Any),
                                                `Rigid)),
                  false),
                 `MetaTypeVar (Point @ 0x7f707d60bff8 `Var ((352,
                                                             (CommonTypes.Linearity.Unl,
                                                              CommonTypes.Restriction.Any),
                                                             `Rigid))))),
     "f", Var.Scope.Local)),
   ([], (Ir.Return (Ir.Variable 231)))))
```
config:
```
typecheck_ir=true
prelude=empty.links
print_types_pretty=false
optimise=false
debug=true
hide_fresh_type_vars=false
show_flavours=true
fail_on_ir_type_error=true
```
Same happens for `concatMap` (error message is longer but I suspect the cause is the same for both):
```
unsafe sig concatMap : ((a) -b-> [c], [a]) -b-> [c]
fun concatMap(f, l) {
  switch (l) {
    case [] -> []
    case hd::tl -> f(hd) ++ concatMap(f, tl)
  }
}
```

Both `map` and `concatMap` IR-typecheck correctly without type signatures.

Checklist of things to do when fixing this:

  * [ ] some tests in `typed_ir` directory (T697b, T698 - and possibly others) use a dummy definition of `concatMap`. These dummy definitions need to be replaced with proper definitions once unsafe signatures are supported in the IR.

**Comment by jamescheney** [comment]
What happens if you give the actual inferred type as the signature?  Seems like it should fail to IR-typecheck unless the IR knows what to do about the unsafe keyword, which I don't think is the case.

**Comment by jstolarek** [comment]
Links infers the type `((a) -b-> [c], [a]) -b-> [c]`, which is identical to what the signature already says (modulo the `unsafe` keyword. If I say:

```
sig map : ((a) -b-> [c], [a]) -b-> [c]
fun map(f, l) {
  switch (l) {
    case []     -> []
    case hd::tl -> f(hd) :: map(f,tl)
  }
}
```
I get:
```
Type error: Using the recursive variable
    `map'
makes this term wild
    `{|b}'
but the currently allowed effects are
    `{wild|a}'
In expression: map.
```
What am I doing wrong?

**Comment by jstolarek** [comment]
A slightly better error message with `print_types_pretty=true`:

```
Type mismatch:
 Expected:
  (a) -b-> c
 Actual:
  (a) ~b~> c
occurring in IR tail computation:
(Ir.Apply ((Ir.TApp ((Ir.Variable 245), [a; { |a }; a])),
   [(Ir.Variable 242); (Ir.Variable 247)]))

```

also, setting `fail_on_ir_type_error=false` (which should have been turned on from the beginning) gives a second error:

```
Incompatible effects; Allowed:
|a
actual effects:
wild|a
occurring in IR tail computation:
(Ir.Apply ((Ir.Variable 242), [(Ir.Variable 246)]))
```

**Comment by dhil** [comment]
> 
> 
> Links infers the type `((a) -b-> [c], [a]) -b-> [c]`, which is identical to what the signature already says (modulo the `unsafe` keyword. If I say:
> 
> ```
> sig map : ((a) -b-> [c], [a]) -b-> [c]
> fun map(f, l) {
>   switch (l) {
>     case []     -> []
>     case hd::tl -> f(hd) :: map(f,tl)
>   }
> }
> ```
> 
> I get:
> 
> ```
> Type error: Using the recursive variable
>     `map'
> makes this term wild
>     `{|b}'
> but the currently allowed effects are
>     `{wild|a}'
> In expression: map.
> ```
> 
> What am I doing wrong?

The ascribed effect signature is missing `wild`. Links does not infer the type `((a) -b-> [c], [a]) -b-> [c]`, rather it infers `((a) ~b~> [c], [a]) ~b~> [c]` (note the `wild` arrows) because `map` is a recursive function.

**Comment by jamescheney** [comment]
Yes, I think I was trying to explain this to Janek the other day and apparently failed.  A (hopefully) temporary workaround could be to introduce an unsafe-coerce operation into the IR that is used solely for ascribing the `unsafe sig` types.  (Obviously it would have many other applications to making more IR code typecheck, much like assuming `False` makes it much easier to prove things.)

Ultimately I would prefer to recognize and translate map/concatMap to dedicated query IR nodes, so that the tame/wild distinction is no longer necessary in the IR.

**Comment by jstolarek** [comment]
> Yes, I think I was trying to explain this to Janek the other day and apparently failed.

No, my comment was written before we spoke :-)

**Comment by jstolarek** [comment]
Preliminary work on branch `js-T691-ir-unsafe-sigs`.

**Comment by jstolarek** [comment]
@dhil, I'm moving discussion on [your comment](https://github.com/links-lang/links/commit/f87a2808e625e5b62eb04902e5ac54896bf6579c#r34638674) here. You suggested to replace:

```
fun_def = binder * (tyvar list * binder list * computation) * 
  binder option * bool * location
```
with
```
fun_def = binder * (tyvar list * binder list * computation) * 
  (binder * bool) option * location
```
I'm not sure whether this is a good idea. During `sugartoir` we always ignore the signature and set the said `binder option` to `None`. Putting `bool` in it would imply that we always discard the safety information as well, which is not what we want. If anything, it would make sense to change the definition in `sugartypes` to include `fun_unsafe_signature` field inside `fun_unsafe_signature`, since indeed safety information makes no sense if there is no explicit signature. Thoughts?

**Comment by dhil** [comment]
I meant to say that the safety information should be part of the `binder` type.

**Comment by jstolarek** [comment]
I am resuming work on this one. (Wow, it has been four months!) @dhil, I still don't understand your idea of putting safe/unsafe information into the `binder` structure. If `binder` was synonymous with a signature then yes, I absolutely agree, but the binders are essentially variables:

```ocaml
type var = int
  [@@deriving show,eq,yojson]
type var_info = Types.datatype * string * Scope.t
  [@@deriving show]
type binder = var * var_info
  [@@deriving show
```
Does safety information on all variable binder make sense?

**Comment by frank-emrich** [comment]
I've done some work on making the IR typechecker aware of unsafe signatures.

My initial idea was to implement something similar to what `TypeSugar` does: If a function has an unsafe signature, don't check its effects but just believe whatever effects the function is annotated with. I've implemented this idea.

However, I've quickly realized that the current propagation of unsafe signatures is already slightly broken in the frontend, and may be more difficult to achieve than we thought.

Consider again the `map` example:
```
unsafe sig map : ((a) -b-> c, [a]) -b-> [c]
fun map(f, l) {
  switch (l) {
    case []     -> []
    case hd::tl -> f(hd) :: map(f,tl)
  }
}
```
The post-frontend AST (shortened) looks like this (we're still in the frontend!):

```
([(Sugartypes.Funs
     [{ Sugartypes.rec_binder =
        ("map", forall a,b::Row,c.((a) -b-> c, [a]) -b-> [c]);
        rec_linearity = CommonTypes.DeclaredLinearity.Unl;
        rec_definition =
        (([(345,
            (CommonTypes.PrimaryKind.Type,
             (CommonTypes.Linearity.Unl, CommonTypes.Restriction.Any)));
            (346,
             (CommonTypes.PrimaryKind.Row,
              (CommonTypes.Linearity.Unl, CommonTypes.Restriction.Any)));
            (347,
             (CommonTypes.PrimaryKind.Type,
              (CommonTypes.Linearity.Unl, CommonTypes.Restriction.Any)))
            ],
          (Some (forall a,b::Row,c.((a) -b-> c, [a]) -b-> [c],
                 [None; None; None]))),
         ([[(Sugartypes.Pattern.Variable ("f", (a) ~b~> c));
             (Sugartypes.Pattern.Variable ("l", [a]))]
            ],
          ( <omitted> ))));
        rec_location = CommonTypes.Location.Unknown;
        rec_signature =
        <omitted>;
        rec_unsafe_signature = true; rec_frozen = true }
       ])
```

The important part here is the line containing
`Sugartypes.Pattern.Variable ("f", (a) ~b~> c));`. This indicates that the function parameter `f` is supposed to have type `(a) ~b~> c`. This contradicts the overall type `forall a,b::Row,c.((a) -b-> c, [a]) -b-> [c]` of the function, which imposes that `f` has type `((a) -b-> c` (note the difference in the effects).  
This means that in the overall type we have the correct effects (as per the unsafe annotation) whereas in the body of the function the parameters are given the original types with the inferred effects.

It seems like a bug that `TypeSugar` doesn't catch this mismatch (when configured to re-run after each transformation). The IR typechecker does, because the list of parameter patterns are translated to `let` bindings (with mandatory type annotations) in the IR during pattern compilation.

In general, it seems like we need to be more careful in the frontend when using unsafe signatures: We have to make sure that once there is an unsafe signature, it must correctly be propagated to all intermediate type annotations in the body. I'm not sure how easy that is under the current design.

**Comment by dhil** [comment]
Here is a thought: Why not use a bit of bidirectionality for unsafe signatures? Instead of running inference, we push the unsafe type inwards. For instance, in the example above we would immediately bind `f` and `l` in the parameter list to their declared types.

**Comment by jamescheney** [comment]
I've been thinking about this one. It seems like the best thing to do would be to arrange for type inference to infer the desired type in the first place, by changing the type inference case for function  calls so that recursive calls of identifiers with unsafe signatures don't attract the `wild` effect.  We could do the same in the IR.

**Comment by jamescheney** [comment]
I've tried this out in a branch and it seems to work so far if we just don't add identifiers that have unsafe signatures to the set of "recursive" function names (which is used to decide whether to give a function the wild effect).  

The only difficulty is that `sortByBase` is defined in terms of the wild `sortBy`, so my approach doesn't work because `sortBy` has (and should have) a wild type.  However, at the cost of a little bit of code duplication, `sortByBase` is OK.

However, one potential problem is that, if we resolve #37 by making pattern-matching against "cons" have a "wild" effect, then this will also need to be suppressed in the bodies of `unsafe sig` functions.

**Comment by jamescheney** [comment]
> making pattern-matching against "cons" have a "wild" effect

(as the IR typechecker already effectively does, implicitly, because we desugar pattern matching of `Cons` to calls to `hd` and `tl`).  Hmm, maybe this wasn't such a great idea after all.
