### ISSUE TITLE
"links" executable name collides with already existing software

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#72]
This is a bit silly but was anyone ever been bothered by the fact that "Links" name - and thus `links` executable as well - collides with [already existing web browser](http://links.twibright.com/)? As part of my local setup I renamed Links the Programming Language executable to `linksc` to avoid name clash. Given that we plan to make a release, perhaps it would be a Good Thing to rename the executable to `linksc` (or something else) to avoid problems on systems that also have the Links web browser installed?
# TODO
- [ ] make any kind of decision.

**Comment by jstolarek** [comment]
Once we decide on executable name we should make sure that this is indeed what is generated and installed in the system. See #61 and #62.

**Comment by LeifW** [comment]
I was naming it "links-lang" locally because of that. Though I imagine less
and less using that browser these days.

On Sep 28, 2016 10:37 AM, "Jan Stolarek" <notifications@github.com> wrote:

This is a bit silly but has anyone ever been bothered by the fact that
"Links" name - and thus links executable as well - collides with already
existing web browser <http://links.twibright.com/>? As part of my local
setup I renamed Links the Programming Language executable to linksc to
avoid name clash. Given that we plan to make a release, perhaps it would be
a Good Thing to rename the executable to linksc (or something else) to
avoid problems on systems that also have the Links web browser installed?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/links-lang/links/issues/72>, or mute the thread

**Comment by jstolarek** [comment]
> I was naming it "links-lang" locally because of that.

I'm glad to hear that it's not only me being affected by this.

Perhaps `linksi` would be a better name, since it is really an interpreter. Let's save `linksc` until we have a compiler.

**Comment by jstolarek** [comment]
@slindley decided on the name "linx".
