### ISSUE TITLE
The test suite runners coherence invariant is broken

### ISSUE THREAD

**Issue by dhil** [links-lang/links#720]
We have two entry points to our main test suite, `test-harness` and `run-tests`. The former runs any individual `.tests`-file, whilst the latter runs all the `.tests`-files in the directory `tests/` by invoking `test-harness` on each file.

Now, it used to be the case that `./run-tests no-db` would only succeed if and only if `./test-harness` would succeed on every `.tests`-file in `tests/`. This is no longer true as witnessed by running the following commands on the master branch:
```bash
$ ./run-tests no-db && echo $?
0
$ ./test-harness tests/typed_ir.tests || echo $?
1
```
I suspect the problem is that `run-tests` attempts to discover test configuration files, and pass any as an additional argument to `test-harness`.

This problem led to a fair amount of confusion in #718 when attempting to debug a failing CI run.

**Comment by frank-emrich** [comment]
I made that change originally, mostly due to a slightly different interpretation of `run-tests` and `test-harness`: In my opinion, the former is a driver for tests (doing stuff like discovering config files), the latter just executes test.
I feel like that is a clearer separation of responsibilities, but of course this breaks the property you describe:
> Now, it used to be the case that ./run-tests no-db would only succeed if and only if ./test-harness would succeed on every .tests-file in tests/

I don't object to this change per se, since Simon seems to share your interpretation of things (cf. his comment in #722 ). However, the change made by that PR evokes that the .config file found in the directory takes precedence over the one supplied as a command-line argument. That sounds like a bad idea: I had cases where I deliberately wanted to run the same `.tests` file using different `.config` files.

**Comment by slindley** [comment]
The prior behaviour didn't work and made it difficult to configure the test suite properly - in particular it is important that we be able to set different configuration operations for different tests in the same test file. The property Daniel describes is important. The configuration options are part of a test.

It might be useful to supplement the now fixed behaviour with additional functionality, but that should not break what we have now.

**Comment by dhil** [comment]
It is wrong to automatically discover configuration files. They should have to be explicitly listed in the test script files.
