### ISSUE TITLE
Question: FreezeML explicit instantiation

### ISSUE THREAD

**Issue by atennapel** [links-lang/links#723]
Why is explicit instantiation needed in FreezeML? Can't you just instantiate any function type in an application?

In `(head ids) 42` why not simply instantiate the `forall t. t -> t` from `head ids`, instead of `(head ids)@ 42`

**Comment by jamescheney** [comment]
In FreezeML, that's not what happens because we don't have a correctness proof for that behavior (yet) - though this may not be hard.  

I think that this may currently be what happens in Links, and it is proposed that this be controlled by a flag until we're sure we understand the implications.  See #687.

However, this is a question about FreezeML (and perhaps how it's implemented in Links), not an issue with Links.  There is a mailing list for this kind of question, which you are very welcome to join:

http://lists.inf.ed.ac.uk/mailman/listinfo/links-users

**Comment by jamescheney** [comment]
Indeed, in Links at the moment this implicit instantiation on application is allowed:

```
links> @load "tests/freezeml_prelude.links";
() : ()
links> ids;
[fun] : [forall a,b::Row.(a) -b-> a]
links> hd(ids);
fun : (a) -> a
links> hd(ids)(42);
42 : Int
```
