### ISSUE TITLE
Diverging computations without the wild effect

### ISSUE THREAD

**Issue by dhil** [links-lang/links#726]
As mentioned in #586, our termination checker does not take the polarity of type variables occurring in datatypes in to account. As a consequence it is possible to ascribe a tame type to the Y combinator in Links. The following example illustrates the problem:
```links
sig y : (((a) -e-> b) -e-> (a) -e-> b) -> (a) -e-> b
fun y(f) {
  fun g(x : (mu r . (((r) -e-> (a) -e-> b))))(a) {
    f(x(x))(a)
  }
  g(g)
}

typename Unit = ();
sig div : ((Unit) -e-> Unit) -> (Unit) -e-> Unit
fun div(self)(()) { self(()) }

links> y(div);
fun : (Unit) -> Unit
```
Running `y(div)(())` causes an infinite loop. Yet the type of the fixed-point of `div` has an empty open row. To be sound, the row should contain the `wild` effect.

The problem is on line 3 in the definition of `g`. Since the recursive type variable `r` (which ranges over a function type) does not occur strictly positively in the function type, the termination checker should expect `wild` to be present in row ranged over by `e`.

**Comment by slindley** [comment]
This has been a known issue for over ten years and I'm surprised it wasn't already mentioned in the issue tracker.

I've removed the label "bug", because it is not necessarily a bug. There are certainly ways of extending the type system to distinguish negative and positive recursive types. It's not clear to me that the extra noise would be worth it though. Given that it seems quite hard to accidentally run into this problem, and the consequences are fairly minor, it may be best to stick with the current design for now.

**Comment by jamescheney** [comment]
@dhil I think that (as with #586) the classic underlying metatheory regarding SN of query expressions in the presence of sums assumes *non-recursive* datatypes with complete pattern matching.  So strictly speaking, we should be forbidding any pattern matching of recursive datatypes, i.e. anything containing `mu`.  That would be a defensible (and easy to check) way to resolve this.  I believe the proof technique also basically works for strictly positive recursive types, i.e. fixed points of polynomial functors, as long as there is no *function* recursion - but I'm not familiar with any proofs of this, and if there is no recursive function calling then there is relatively little point in allowing recursion in the datatypes.

We aren't statically checking either that datatypes are strictly positive or that pattern matching is complete, so it is a proof obligation on the programmer to avoid indulging in either of these luxuries if they want queries to behave.  In fact, @fehrenbach found a use for letrec in query expressions, and there is a partial correctness guarantee that says that *if* a query expression defined using recursion terminates, *then* the normal form still corresponds to an NRC query.  

So I can imagine a case for going the other way, at some point: treating this as a feature rather than a bug,  allowing recursive functions (but not printing etc.) to be "tame" but again emphasizing that Links leaves ultimate responsibility of ensuring completeness/termination in the programmer's hands.

**Comment by slindley** [comment]
@dhil, it does have some similarities with #544, but it differs in important ways. As @jamescheney said non-termination is not necessarily as bad as the kind of type soundness violation in #544. Unlike #544 I have thought quite a bit about the implications of trying to rule out diverging data types using an extension to the type system on several occasions in the past and I am not convinced that we want to enable such a feature by default (as the costs may be unpalatable). It might be worth experimenting with a way of distinguishing positive data types, but it's quite possible we will never adopt such a design.

@jamescheney, it is important in practice that we allow inductive data types in queries, because they are useful when composing queries.

@jamescheney, there are some dangers of actively embracing non-termination in queries. The obvious one is that query normalisation may not terminate. Another issue is that it provides new ways to run out of memory (by generating inifinitely large queries) - though we can of course do that explicitly in the host language, even if we disallow negative recursive types in queries.

**Comment by slindley** [comment]
The same argument applies: you're unlikely to accidentally write a non-terminating function (you'd need to explicitly implement a fix-point operator using negative recursive types), so let's not worry about it for now.
