### ISSUE TITLE
DesugarFuns introduces linear variables in non-linear functions

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#795]
Compiling:

```
fun curry(f) {
  fun (x)(y) { f(x,y) }
}
```
with the following settings:
```
prelude=empty.links
optimise=false
debug=true
recheck_frontend_transformations=true
```
Produces:
```
error: transformation pass 'funs' produced an ill-typed program.

:0: Type error: Variable x of linear type 481::Any was used in a non-linear function definition
In expression: <dummy>.
```
Use this settings for more detailed debug output:

```
hide_fresh_type_vars=false
show_flavours=true
show_quantifiers=true
print_types_pretty=true
show_pre_frontend_ast=true
show_post_frontend_ast=true
show_raw_type_vars=true
recheck_frontend_transformations_dump=true
```

**Comment by jstolarek** [comment]
Also, this might be the cause of #574

**Comment by slindley** [comment]
Ah, yes! We never made any effort to ensure that linearity is preserved by compilation (e.g. pattern matching compilation for products can violate linearity), but this is a plain frontend bug which should be fixed. The underlying issue is exhibited by a simpler example:

    links> fun (x)(y) {(x, y)};
    fun : (a::Any) -> (c::Any) -> (a::Any, c::Any)

Compare this with:

    links> fun (x){fun (y) {(x, y)}};
    fun : (a) -> (c::Any) -> (a, c::Any)

The latter has the correct type. The former does not. It is unsound to allow a linear variable to be captured by a non-linear function.

    links> fun f(x)(y) {(x, y)};
    f = fun : (a::Any) -> (c::Any) -> (a::Any, c::Any)
    links> fun (x, y, z) {var g = f(x); (g(y), g(z))};
    fun : (a::Any, b::Any, b::Any) -> ((a::Any, b::Any), (a::Any, b::Any))

Here the linear variable `x` is used twice (once in each invocation of `g`)! The correct fix is to make sure that the first example above is treated just like the second example. The rule is that for a curried non-linear function only the very last argument can ever be linear (because partial application allows captured variables to be reused).

**Comment by slindley** [comment]
We can of course have multiple linear arguments if the function is not curried:

    links> fun (x, y) {(x, y)};
    fun : (a::Any, b::Any) -> (a::Any, b::Any)

**Comment by jstolarek** [comment]
> The rule is that for a curried non-linear function only the very last argument can ever be linear (because partial application allows captured variables to be reused).

In that case I am leaning towards putting a fix into the `FunLit` case in `typeSugar`, right after we typecheck the patterns (pattern variables are assigned `Any` kind during typechceking by default).
