### ISSUE TITLE
Todo list (server) is broken on master

### ISSUE THREAD

**Issue by dhil** [links-lang/links#807]
The `Todo list (server)` example from the example page is broken on the master branch. It produces the following error upon attempting to complete an item

```
Links Error

***: Error: "Assert_failure core/query/query.ml:1102:6" 
```

Steps to reproduce:
1. Enter an item, e.g. "test"
2. Press "Add item"
3. Press "Done"

**Comment by dhil** [comment]
The assertion failure is triggered by the default case in the `base` function in `query/query.ml`
```
and base : Sql.index -> Q.t -> Sql.base = fun index ->
  let open Q in
  function
    ...
    | e ->
      Debug.print ("Not a base expression: " ^ Q.show e);
      assert false
```

**Comment by wricciot** [comment]
No big deal: the delete query wasn't normalized. I'm surprised this went overlooked for such a long time.

**Comment by jamescheney** [comment]
I just ran across this bug again since it is present in v0.9.1 and breaks the todo_db tutorial example.  It looks like this was introduced inadvertently by #624 which changed `Eval.computation` so that it just translates IR to query code, but did not normalize.  It would be good to get an update out that includes this fix.  

I guess this is a further argument for checking the web examples (and tutorials) before creating a new version (i.e. headless web testing #851).  Though in this case the problem could have been caught by a database test; right now there aren't any database tests that exercise this code path.
