### ISSUE TITLE
Query flatness checking is too strict

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#835]
If we run this query (with shredding/relax_query_type_constraint disabled):

```
 # should succeed but fails because of nested intermediate type/type error

 query { for (y <- for (x <-- factorials) [(b=[])])
         [(a=0)]};
```
 we get a type error:
```
Unification error: Cannot unify the Base row variable 6645 with the non-Base row b:[_::Any].
<stdin>:1: Type error: A database comprehension must return a list of records of base type, but the expression
    `[(b=[])]'
has type
    `[(b:[a::Any])]'
In expression: for (x <-- factorials) [(b=[])].

```
This is wrong because the above query only introduced nesting inside the query and the result type is not nested.  Therefore normalization will get rid of it.

If instead we write this equivalent query:
```
# should be equivalent but succeeds
 query { for (y <- for (x <- asList( factorials)) [(b=[])])
         [(a=0)]};
```
it typechecks and we do get the right answer.

Moreover, if we enable shredding and relax_query_type_constraint and run these queries with the flat query evaluator we get a run-time error both times:

```
***: Runtime error: Incompatible query evaluation annotations. Expected flat, got nested. 
```

**Comment by jamescheney** [comment]
@SimonJF I wondered whether this behavior might have been inadvertently introduced in #757.  Before, I'm certain we were only checking for flatness of the query overall result.

**Comment by jamescheney** [comment]
Possibly relatedly, there is also something wrong with (syntactically) running completely flat queries when shredding is enabled.  Both of the following
```
 query flat { for (x <--factorials) [(a=x.i,b=x.f)]};
 query flat { for (x <- asList(factorials)) [(a=x.i,b=x.f)]};

```
result in 
```
***: Runtime error: Incompatible query evaluation annotations. Expected flat, got nested. 
```
and I'm not sure why.  Both run fine with shredding disabled.

**Comment by SimonJF** [comment]
Thanks for picking this up. I'll take a look.

**Comment by SimonJF** [comment]
OK. There are a few things here. First:

Your initial problem:

```
 # should succeed but fails because of nested intermediate type/type error

 query { for (y <- for (x <-- factorials) [(b=[])])
         [(a=0)]};
```

is unrelated to #757, since it was present before the patch. I'll have a look at that in a bit.

---

Your second issue is the combination of two issues: one was a bizarre behaviour in the typechecker, and one was a bad design decision that I made in #757.

When you write:
```
 query flat { for (x <--factorials) [(a=x.i,b=x.f)]};
```

you're saying that you wish to evaluate the given query using the flat evaluator. Now, there was a very strange behaviour at the end of the `Iteration` case of `typeSugar`:

```
            if is_query
            then Query (None, QueryPolicy.Default, with_pos pos e, Some (typ body)), typ body, us
            else e, typ body, us
```
which essentially wraps every iteration with another `Query` block. This gives us:

```
 query flat { query { for (x <--factorials) [(a=x.i,b=x.f)]} };
```

Now, normally this would be fine since nested query blocks are immediately normalised. However, I now realise a design decision I made was wrong. Given the lack of a query annotation, the evaluator chooses based on the current `shredding` setting, and if that's set to true, we essentially have:

```
 query flat { query nested { for (x <--factorials) [(a=x.i,b=x.f)]} };
```

...hence the error.

So, there are two things to do here:

  1. The wrapping behaviour should not be in `typeSugar`. I realise it's necessary in order to ensure that table accesses are indeed put inside query blocks, but this should not happen during typechecking! It'd be best as a post-TC desugaring.

  2. Rework the default behaviour to just check against the currently-selected evaluator.

**Comment by jamescheney** [comment]
So here's what appears to be happening:

- `for(x <-- t)` gets translated to `Iteration([Table(...)],...)`
- `for(x <- asList(t))` gets translated to `Iteration([List(...)],...)`
-  `typeSugar` typechecks `Iteration`s by first determining whether they are queries.  If so (and shredding / relaxed query typechecking are not enabled) then the return type of the query is forced to be a (closed) row of base types.  The `is_query` test is syntactic, based on whether the `Table` construct is present in any of the generators.
- this happens before desugaring passes such as `wrapTableIterators` and `desugarFors`.

I think the syntactic heuristic for `is_query` is wrong to use during typechecking; clearly it leads to different behavior for expressions that should be equivalent as mentioned above.  Also, this approach to typechecking `Iteration` seems to predate the introduction of the `query` keyword, which seems to be a more natural place to check that the return type is flat (if it is required to be).  

So, my suggestion for fixing this issue would be to remove the `is_query` check from the `Iteration` typechecking case entirely, and instead do this check (if needed) in the `Query` case.  There is another piece of conditional code in the `Iteration` case which forces the effect row of an `Iteration` to be a closed empty row if it `is_query` (that is, this enforces that queries are tame).  This can/should probably also be enforced in the `Query` case too.  In fact it already appears to be.

`wrapTableIterators` is already deciding whether an `Iteration` is a query based on the syntactic form of its generators, and hence will only insert `query` constructors around `<--` iterations (if there isn't an enclosing one already), not `<- asList` ones.  So, it should always be (at least as) correct to check the query return type at the `Query` case.  While this is probably a sensible heuristic for inserting query keywords (since the programmer almost certainly doesn't intend `<--`-comprehensions to be run on the server), longer-term I think it would be a bit cleaner to rethink this, and enforce `query` hygiene using the type system (requiring a query keyword if the query contains table references, maybe also enforcing that all the table references are from the same database) instead of ad hoc conditional checks/desugaring, but that's a separate issue.  (Tracking table / database references in the type system would be useful elsewhere, for example in typechecking lens predicates.)

@SimonJF @slindley ??

**Comment by jamescheney** [comment]
Ugh.  OK, so the problem with just disabling the `is_query` conditional code in `Iteration` is that if there isn't in fact a query keyword, then the effects won't match (e.g. if we try to call a tame function from within a `for(<--)` comprehension called from a wild context, like in line 121 of wine.links).  The extra `query` keywords aren't going to be added until after initial typechecking, so, we would still need to emulate this behavior earlier if we want to preserve exact compatibility.  If we're willing to have to add query keywords in a few places where we didn't have to before, then what I had in mind looks like it works (at least, all tests pass if I add the query keyword to wine.links:121.

Can we live with that?

**Comment by SimonJF** [comment]
In all honesty, I was very surprised that `<--` implicitly added `query` blocks in any case. So I'm personally all for being more explicit and allowing us to get rid of `wrapTableIterators`.

**Comment by jamescheney** [comment]
Following further discussion I suggest that we  consider specializing the type of asList to have the tame (absence of wild) effect, so that it *must* execute in a tame environment (and with no other effects).  We could then desugar `for(<--)` to `for(<- asList)` just like we pretend to do in various papers.

This would force us to put query blocks around all `for(<--)` or `for(<- asList)` iterations, to make it explicit which parts of the program are queries, and we wouldn't have to infer them and can get rid of the `wrapTableIterators` pass.  

I think this should be a separate issue though since it would be a larger, more breaking change.

**Comment by slindley** [comment]
The `<--` notation has always been intended as syntactic sugar. As such more weight is put on conciseness and convenience and less weight on compositionality in its design than we would do for a built-in language construct.

The current design is concise and convenient in that it avoids the need to write query blocks in the most common case. It is also safe in the sense that it doesn't inadvertently lead to loading an entire table into memory, e.g. by returning a nested data type - which is what could happen if we instead wrapped `query` around `asList` (I'm sure that that would be a mistake).

Where the current design can be surprising and annoying is that it gets in the way of composing queries that use nested data - the fix is to use `(x <- asList(t))` instead of `(x <-- t)`. If we had a more concise abbreviation for `asList` then this would be less annoying.

I think that the forms `(x <-- t)` and `(x <- asList(t))` are both useful in real programs. However, there's a reasonable case to be made that despite the extra ink required in explicitly writing `query`, this information is so critical in practice that we would actually be doing the programmer a service by insisting that they always write it out. However, that leads me to the conclusion that ideally the syntactic sugar should really be for `asList(t)` rather than for `(x <- asList(t))`.

I guess a possible advantage of taking something like `(x <-- t)` to be syntactic sugar for `(x <- asList(t))` is that it might avoid polluting the space of lexemes in a way that syntactic sugar for plain `asList(t)` would be liable to do.

**Comment by jamescheney** [comment]
Really, `for(x<--t) e` is syntactic sugar for `query {for(x <- asList(t)) e` (and more generally, for any `Iteration` that contains `<--`).  I can live with this design, as long as the error message you get if you mistakenly use `for(x<--t)` to construct a nested intermediate value becomes more informative, for example to say "if you really meant to construct a nested intermediate result, use `asList`).  But I prefer the stricter effect-checking (and laxer flatness checking) proposed in #841.  

You seem to be suggesting a different approach in the following sentence:

> However, that leads me to the conclusion that ideally the syntactic sugar should really be for asList(t) rather than for (x <- asList(t)).

but I don't understand what this proposal is, or how it would help ensure that query keywords (implicit or explicit) or flatness checking definitely happen when a query is performed, or that `asList` is always performed inside a `query`.  #841 ensures both.

**Comment by slindley** [comment]
Currently `for (x <-- t) e` is syntactic sugar for `query {for (x <- asList(t)) e}`. Changing it to `for (x <- asList(t)) e` in some sense amounts to defining `- t` as syntactic sugar for `asList(t)`. I was mooting the idea of writing something like`$t` (picking a character at random) as syntactic sugar for `asList(t)`. Writing `for (x <- $t) e` takes no more characters than `for (x <-- t) e` but the syntax would be slightly more uniform. My counterargument to my own suggestion is that that would use up a lexeme - in this case `$`.

If we do adopt a syntax that doesn't automatically wrap `query` around the comprehension, then we should certainly go for a stricter typing to ensure that the comprehension is tame - otherwise we risk accidentally pulling in whole tables.
