### ISSUE TITLE
Multicolour mandlebrot and breakout examples are broken

### ISSUE THREAD

**Issue by slindley** [links-lang/links#860]
When making changes to the codebase it is important to periodically *manually* check that the example web applications continue to work. Even if we had some form of headless testing it would be hard to pick up the current bugs:

  1) The multicoloured mandlebrot example does draw something, but it looks like a pretty weird Mandlebrot set to me!
  2) The breakout bat is now missing (at least on Firefox / Chrome on my Linux machine) - which makes it rather hard to play!

**Comment by jamescheney** [comment]
Agreed, and I'm just as guilty of this as anyone.  (I tend to assume that if I haven't changed anything to do with the client-side or web code then I haven't broken anything, which is not a valid assumption).

Git bisect to he rescue!  This problem doesn't appear in 0.9.1 (though the todo DB example in the tutorial was broken, illustrating that we should *also* be testing the database + Web examples at least before minting a new version).  The problem was introduced in this commit:

65bc0ef  (i.e. PR #806)

so my guess is that some of the examples relied on the previous behavior of operator precedence parsing, i.e. this may not be a bug introduced in Links, but a situation where Links code was relying on previous, incorrect (or at least unpredictable) parsing behavior.  

I suppose this is something that could have been caught by ordinary tests, but perhaps we could also be putting more asserts in the web tests, so that it's more obvious when something goes wrong.

Perhaps when fixing this, we can also increase the speed of the breakout bat so that the game is minimally playable - at least for me, it moves too slowly to ever hit the ball...

**Comment by jamescheney** [comment]
Nope, I'm wrong:

```
links> 42.0 +. 1.0 *. 42.0 == 42.0 +. (1.0 *. 42.0);
true : Bool
links> 42.0 -. 1.0 *. 42.0 == 42.0 -. (1.0 *. 42.0);
false : Bool
```

The culprit seems to be a line declaring the precedence of the `.-` operation to be `infixl6` ( `.-`  isn't a legal operation in Links) instead of the `-.` operation, which was copied into `shunting.ml` from `lexer.mll`.
```
    ".-" , infixl6;
```
This code dates to... wait for it... 

August 3, 2006 f1974696

Apparently the previous behavior of precedence parsing has been masking this all that time, and #806 unmasked it.

**Comment by dhil** [comment]
Thanks for working this out. I tend to check all the examples before committing a PR, but I must have forgotten in this instance. Apologies.

**Comment by yallop** [comment]
> This code dates to... wait for it...
> 
> August 3, 2006 f197469

Oops.
