### ISSUE TITLE
Desugaring revalidation errors in prelude

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#865]
If validation after every pass is enabled, typechecking the `reproduce` function from `prelude.links` yields the following mysterious error:

```
error: transformation pass 'cp' produced an ill-typed program.

Type error: Inconsistent quantifiers, expected: 
    forall a::Session,b::Row.(AP (a::Session), (a::Session) {SessionFail:() {}-> [||]}~> ()) ~b~> ()
actual: 
    forall a::Session,b::Row.(AP (a::Session), (a::Session) {SessionFail:() {}-> [||]}~> ()) ~b~> ()

In expression: fun reproduce(ap, f) {
  var x = accept(ap);
  var _ = spawn {f(x)};
  reproduce(ap, f)
}.
```
The quantifiers don't look inconsistent to me, however, maybe this is hidden by pretty-printing.  Looking at the raw types wasn't that much more enlightening.

Also, after commenting that out, typechecking `makeEndBang` yields:
```
error: transformation pass 'funs' produced an ill-typed program.

Type error: Because of the value restriction there can be no
free rigid type variables at an ungeneralisable binding site,
but the type `Process ({ |a })' has free rigid type variables.
In expression: var _ = spawn {
     var c = accept(ap);
     wait(c)
  };.
```

**Comment by jstolarek** [comment]
Which commit and what config was used to obtain this?

**Comment by jamescheney** [comment]
Current master: b535b8b9bbdfc814c9f54be90b33c63ae4e9bddf

Configuration:

```
prelude=/dev/null
optimise=false
hide_fresh_type_vars=false
show_flavours=true
recheck_frontend_transformations=true
debug=true
```

then do `../links --config=config prelude.links` (to work in a subdirectory `links/tmp` with a temporary copy of the prelude)

**Comment by slindley** [comment]
That this bug exists tells us that there's something missing from our tests. Whilst it probably takes too long to run all of our tests with `recheck_frontend_transformations=true` we should at least test the prelude once with this flag enabled!

**Comment by slindley** [comment]
The commit that introduced the regression is this one: d72e68d156e439caa6440bb07ff67782492b4432

**Comment by slindley** [comment]
The immediate cause of the error is the use of the type variable renamer when type checking recursive functions. It's unclear why this should be necessary in any case, but the problem is that the renamer is broken. For some reason it does not rename the type variables in the `rec_signature` field of a recursive function binding and the error we're seeing is reporting the mismatch between the type variables in the definition and in the signature. I suspect there may be further issues here relating to refactoring of datatype desugaring - the frontend representation of the signature datatype also needs renaming and isn't.

Disabling the renamer fixes this problem, but then an error occurs later on in the frontend (in function desugaring).

**Comment by jamescheney** [comment]
This much smaller problem reproduces (ha) the first error:
```
sig reproduce : forall a.(a) {}~> ()
fun reproduce(f) {
  reproduce(f)
}
```
I guess reproduce just happens to be the only recursive function in the prelude with a quantified polymorphic signature.  

The second one can be shortened to this which still produces the same error about generalizing free rigid type variables.
```
var asdf = spawn { () };
()
```

**Comment by slindley** [comment]
The error in function desugaring arises because of the generalisation that occurs inside function literals. This seems harmless enough, and indeed it would be if the implementation of generalisation was a bit more careful. Here's roughly what's going on. The following

    var (z : { |%e}) = spawnAt { |%e} (fun () {...});

is intended to be desugared into code that explicitly names, and generalises, the anonymous function:

    var (z : { |%e}) = spawnAt [{ |%e}] (fun f[e'::Row]() {...}; f[{ |%e}])

but instead it comes out more like this

    var (z : { |e}) = spawnAt [{ |e}] (fun f[e::Row]() {...}; f[{ |e}])

(using suitable notation for type abstraction and type application).

The row variable `%e` doesn't appear in the type environment so it gets generalised in the type of the anonymous function. But this operation incorrectly mutates the `%e`s appearing in the type of `z` and applied as a type parameter to `spawnAt` turning them into rigid variables.

One solution is to do a more careful implementation of generalisation that renames variables by traversing the term rather than using mutation. This may be worthwhile implementing anyway. (I'm sure I talked to Jonathan about doing this at some point.)

Another solution is to disable the generalisation. This is sound, but breaks some of the test cases as well as the IR checker (which is probably making some dubious assumptions anyway).

**Comment by slindley** [comment]
Summary:

  * The renamer is unnecessary in the places it is currently used.
  * The renamer is broken.
  * Desugaring of anonymous functions is broken because its use of generalisation is unsound.

**Comment by jamescheney** [comment]
The fact that disabling the renamer fixes the problem doesn't necessarily imply that the renamer is broken. I looked earlier (in the diff for d72e68d156e439caa6440bb07ff67782492b4432) and didn't see anything obviously wrong, nor anything obviously different between how nonrecursive and recursive function signatures are renamed.  Thus, I would expect to see the same problem happen with nonrecursive functions with explicitly quantified signatures, e.g.
```
sig reproduce : forall a.(a) {}~> ()
fun reproduce( f) {
}
```
Since the above doesn't exhibit the problem, that makes me think that the problem has to do with a difference between how the inferred type annotations are checked against quantifier signatures for recursive vs. non-recursive functions in typeSugar.  Having looked at those places, though, I'm none the wiser.  My totally uninformed conjecture would be that renaming happens to expose a place where we are testing quantifiers for equality where we should be checking for alpha-equivalence (or, a place where we should clearly document invariants involving the type signatures and annotations that are sensitive to alpha-renaming and should not be so renamed).

**Comment by slindley** [comment]
I may not have made myself clear, but my evidence that the renamer is broken is based on inserting debugging messages printing out a function definition before and after running the renamer and observing that it doesn't rename quantifiers in type signatures! It *is* broken! I also looked at the code and it wasn't obvious to me *why* it doesn't rename quantifiers in type signatures.

**Comment by jamescheney** [comment]
Ah, OK.  The renamer seems to traverse the AST and rename the quantifier lists in the types associated with function or recursive function nodes, but when traversing foralls elsewhere the variables are shadowed so that renaming doesn't occur.

However, provided the signatures are closed, this shouldn't matter if the typechecker is invariant under alpha-renaming of signatures.  So what is "broken" depends, I guess, on what is expected: maybe the renamer should be fully alpha-renaming the signatures too, but even then I think we'd still be seeing similar behavior in typeSugar, because the existing behavior is trying to test literal equality of quantifiers in two different binding lists.  My bias would be that not respecting alpha-equivalence is what is "broken".

**Comment by slindley** [comment]
Some of the links codebase relies on the invariant that the type variables bound by the function and its type signature have the same name. That may not be ideal, but it is that way by design. The renamer is broken in the sense that it violates that invariant... though this is somewhat moot given that the renamer is unnecessary in the places that it is currently used.

**Comment by jstolarek** [comment]
@slindley, above you say:

> The renamer is unnecessary in the places it is currently used.

but in [this comment](https://github.com/links-lang/links/pull/774#issuecomment-545987338) you said (emphasis mine):

> The crucial point is that the current goal is to proceed on the basis that there is no guarantee that bound type variables have unique names. A key implication of non-uniqueness is that in the escape check we must freshen the bound variables (in the body of the function) as the escape check relies on checking that these variable do not appear in the environment. So what needs to happen is if a function has a non-empty collection of type variables, then those **type variables must be freshened immediately before checking the body of the function**.

I agree with your diagnosis why the current implementation of renamer does not work correctly because it doesn't freshen the signature, but I don't see what would be a correct place to call the renamer.  At the moment renamer is called immediately before checking the body of a function, just like you said in the cited comment.

> That this bug exists tells us that there's something missing from our tests. Whilst it probably takes too long to run all of our tests with recheck_frontend_transformations=true we should at least test the prelude once with this flag enabled!

I believe the reason why we don't have such a test is because rechecking frontend transformations on prelude currently doesn't work at all, with and without the renamer.  We can add such a test and mark it as expected failure if you think that makes sense.  I'm in general strongly in favour of having such tests because then we immediately notice if something gets accidentally fixed and I think we should have an "expected broken" test for every bug report. Sadly, it seems that we currently don't have a facility to test for exact error messages, which means we will only notice when something gets fixed but we won't notice if an error message changes to a different one.

**Comment by jstolarek** [comment]
> For some reason it does not rename the type variables in the `rec_signature` field of a recursive function binding

This also doesn't work as intended for non-recursive function bindings.

**Comment by slindley** [comment]
Ah... I was wrong about it not being necessary then; sorry for the confusion - I'd forgotten about the escape check! I should have said that renaming doesn't seem to be necessary for loading the prelude or running the test cases... but that doesn't really tell us much given that the tests don't bother rerunning the type checker after each frontend translation. We really need to get back to a situation in which the frontend transformations and the type checker are sound.

A more robust alternative to renaming the signature would be to ensure that the code for type checking functions can cope with the signature and type variables parameters having different names. I think @jamescheney was implying that doing something along these lines might be preferable to changing the renamer to maintain the invariant that signatures and type variable parameters match up.

Separately from this, we should also make the implementation of generalisation more robust. Currently it cheats by updating the generalised variables in place to make them rigid, which is sometimes unsound. The correct thing to do is to perform renaming.

All of this fits in with a more general improvement that we should make as part of phase 2 of refactoring types (#637) whereby we should allow type variables to exist without being inside a `Meta` constructor.

**Comment by jamescheney** [comment]
> I think @jamescheney was implying that doing something along these lines might be preferable to changing the renamer to maintain the invariant that signatures and type variable parameters match up.

I was indeed impliying something along those lines.  But, I was not explicitly suggesting that because I'm not sure that the alternative makes sense (or is a good idea).  The current checks that rely on equality of bound variable names in different places appear to just check that one quantifier list is a *subset* of the other (also ignoring order) but I can't easily untangle the logic and it seems to differ subtly between the nonrecursive and recursive cases.  However, it also seems that after the *first* run of typeSugar, all functions/ recursive functions are also marked as "frozen", and so their types are not re-generalized but we just use the previously inferred type (seemingly making the signature itself completely redundant from then on!)  Then the renamer stupidly renames just one of these and the checks fail.

The alternative of clearly documenting that there is a data structure invariant that the "bound" names need to be aligned, and modifying the renamer to enforce it, seems the right thing to do at the moment to me.  Is the following description of the invariant correct:

- After the first (if successful) run of `typeSugar.type_check`:
  * All `fun_frozen` and `rec_frozen` flags on `Fun` and `Funs` are `true`
  * All function type annotations on such functions are present, and syntactically equal to the ascribed signature (if  also present)

There already seems to be code that checkes to see if the inferred type annotation is present, and ignores the signature if so - so maybe the error is really with the logic of these parts of `typeSugar`.  If so, perhaps changing the typechecker so that after the first inference pass (when inferred type annotations are filled in) the signatures are `None` so that these conflicts never arise.  Perhaps we could also check that the inferred signature and annotation are not both present, in the renamer.

**Comment by jamescheney** [comment]
> perhaps changing the typechecker so that after the first inference pass (when inferred type annotations are filled in) the signatures are None

This does seem to "work" (i.e. resolve the first problem and not break any tests).  However, maybe it would be more satisfying to find the actual reason why the signatures are being used after the first typechecking pass.  

This leaves the problem encountered with `makeEndBang`.

**Comment by jstolarek** [comment]
> A more robust alternative to renaming the signature would be to ensure that the code for type checking functions can cope with the signature and type variables parameters having different names. 

I think the issue of having distinct variable names for type signatures and lambdas is orthogonal from the need to have a renamer. We need the renamer to do the occurs check and we will still need it even if we allow names of forall- and big-lambda-bound variables to differ. 

> @jamescheney was implying that doing something along these lines might be preferable to changing the renamer to maintain the invariant that signatures and type variable parameters match up.

We looked into this with @frank-emrich a while back. I vaguely recall that the unification variables were shared between the type signature and the body of a lambda abstraction. I don't recall the exact details but with a bit of luck they are recorded somewhere in the comments or email. I'll try to unbury it.

> maybe it would be more satisfying to find the actual reason why the signatures are being used after the first typechecking pass.

The reason why renaming didn't work for signatures was weird.  Here's the relevant code:

```ocaml
method! typ : datatype -> (datatype * 'self_type) = function
  | ForAll (qs, t) ->
     let inst_map = shadow_vars inst_map qs in
     let t', _ = {< inst_map >}#typ t in
     ForAll (qs, t'), o
  | t -> super#typ t
```

`shadow_vars` is the relevant bit - as the name suggests it's responsible for shadowing those variables in a renaming that are also defined in a forall.  For example if we have a renaming map `[a => b, c => d]` (which means: rename all occurrences of `a` to `b` and all occurrences of `c` to `d`) and we encounter a signature `forall a. ...` then we consider the forall-bound `a` to be shadowing the `a` in the domain of the substitution - hence we are left with a substitution `[c => d]`. Except that defeats the whole purpose of renaming! Fixing this *seems* easy but, since this is so obviously wrong, I fear there is some deeper intention here, which sadly I was unable to uncover. I'll submit a PR once it passes the CI.

**Comment by frank-emrich** [comment]
> We looked into this with @frank-emrich a while back. I vaguely recall that the unification variables were shared between the type signature and the body of a lambda abstraction. I don't recall the exact details but with a bit of luck they are recorded somewhere in the comments or email. I'll try to unbury it.

Sorry, but I don't remember the details of this, either :(

**Comment by jstolarek** [comment]
@frank-emrich, I looked at the code in typeSugar and I'm beginning to recall this had something to do with code in the `Fun` case, and in particular:

  1. `resolve_type_annotation` being used to determine the type signature
  2. unification of `ft_mono` and `shape`, where `shape` contains a fresh tyvar for the return type
  3. typechecking of the body, followed by another unification

I'll eyeball the code some more tomorrow, maybe I'll manage to put all of this together again.

**Comment by jstolarek** [comment]
1. Quantifier renaming bug is now fixed.
  2. I created #871 to track the problems with generalisation being unsound. I also added a test case that is expected to fail at the moment.
  3. I added a test that compile Prelude with `recheck_frontend_transformations=true`. At the moment it is expected to return an error. 

*\<rant\>I want to be able to mark tests as known to be broken!\</rant\>*
