### ISSUE TITLE
"Incompatible effects" IR typechecking error

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#873]
Compiling the following function from Prelude:

```
sig freshResource : () ~> ()
fun freshResource() {
  escape esc in {
    redirect("?_k=" ^^ unsafePickleCont(fun () {esc(())})); exit([])
  }
}
```
produces an IR typechecking error:
```
***: IR Type Error: Incompatible effects:
 Allowed:
  wild
 Actual:
  wild|350
occurring in IR tail computation:
(Ir.Apply ((Ir.TApp ((Ir.Variable 172), [{ |wild|%365 }; %359; { |350 }])),
   [(Ir.Variable 228)]))
```
Reproduced on 2b26e2fe with following config:
```
typecheck_ir=true
fail_on_ir_type_error=true
prelude=tests/empty_prelude.links
optimise=false
debug=true
print_types_pretty=false
hide_fresh_type_vars=false
show_flavours=true
show_quantifiers=true
print_types_pretty=true
show_raw_type_vars=true
```

See #697 for a similar error but with a different cause.

**Comment by jamescheney** [comment]
Seems related to #23.

**Comment by jamescheney** [comment]
The following minimal example exhibits the same incompatible effects error.  (Some of the basic examples in `continuations.tests` also exhibit this problem.)
```
fun () {
  escape esc in {
    esc(())
  }
}
```
with error
```
***: IR Type Error: Incompatible effects:
 Allowed:
  wild
 Actual:
  wild|357
occurring in IR tail computation:
(Ir.Apply ((Ir.Variable 227), [(Ir.Extend ({}, None))])) 
```

Removing the enclosing `fun () {...}` results in no error being reported.  Also, the following morally equivalent code:
```
escape e in { (fun (esc) { esc(()) })(e) }
```
also results in no error report - which suggests that one workaround could be to desugar general escapes as follows:
```
escape x {e} --> escape x { (fun (x){e})(x) }
```
so as to avoid whatever bug is coming up in the translation of escape to call/cc.

It may also be relevant that, if `debug` and `show_compiled_ir` are enabled, we see the following debug error message concerning the same type variable 357 as the one leading to a type error:
```
Row variable where row expected:(Types.Meta
   Point @ 0x10ec78f90 (Types.Var
                          (357,
                           (CommonTypes.PrimaryKind.Row,
                            (CommonTypes.Linearity.Unl,
                             CommonTypes.Restriction.Any)),
                           `Rigid)))
```
which is generated by type printing: https://github.com/links-lang/links/blob/6f812d1bbc452c1e5aa1d24aa21e33d1f33e83e3/core/types.ml#L2353 with a nearby comment indicating that this is a case that should never happen.  However, this warning doesn't appear with the original `freshResource` example.

**Comment by jamescheney** [comment]
Oops, I got confused; this works
```
escape e in { (fun (esc) { esc(()) })(e) }
```
but the reason it works is the same as why removing the outer `fun () {...}` worked: the wrong effect context (the one inherited from around the escape) is being used to build the type of the function that we eventally pass to `CallCC`.  Thus, this still doesn't work:
```
fun () { escape e in { (fun (esc) { esc(()) })(e) } }
```
and my suggestion that desugaring would help is wrong.

Likewise, this does not work:
```
sig foo : () {a}~> ()
fun foo () {
  escape e in { (fun (esc) { esc(()) })(e) }
}
```
with error 
```
***: IR Type Error: Incompatible effects:
 Allowed:
  wild
 Actual:
  |wild|a:() {}-> ()
occurring in IR tail computation:
(Ir.Apply ((Ir.Variable 230), [(Ir.Variable 227)])) 
```
but this does work
```
sig foo : () {}~> ()
fun foo () {
  escape e in { (fun (esc) { esc(()) })(e) }
}
```

I think the basic problem is similar to that fixed for list pattern desugaring in #864; we should probably be using the effect from the continuation type rather than the effect of the ambient context, when creating the function to pass to `CallCC`, since otherwise if we are not at the toplevel then type inference infers a polymorphic wild effect which doesn't match the closed wild effect row inherited from the toplevel.

**Comment by jamescheney** [comment]
Some partial progress (see branch `issue-873`): reusing the effect from the continuation function type to build the function we pass to `CallCC` makes both of the following work:
```
fun () {
  escape esc in { esc(()) }
}
```
and 
```
sig foo : () {a}~> ()
fun foo () {
  escape e in { (fun (esc) { esc(()) })(e) }
}
```
However, `freshResource` itself still does not typecheck because of a different problem:
```
***: IR Type Error: Incompatible effects:
 Allowed:
  wild|%365
 Actual:
  wild|350
occurring in IR tail computation:
(Ir.Apply ((Ir.TApp ((Ir.Variable 172), [{ |wild|%365 }; %359; { |350 }])),
   [(Ir.Variable 228)])) 
```
i.e. there is still something wrong, seemingly to do with flexible variables that should have been unified earlier not being so unified.  

The proximate issue seems to be that `unsafePickleCont` takes an arbitrary (wild or not) function and has the wild effect, and the effect of the function being passed to unsafePickleCont is never unified with anything (other than wild because the continuation `esc` is wild.)  However, when we translate to IR, it is too late to do this unification.

As an experiment, the following alternative version of `freshResource` does type-check:
```
# From Prelude
sig freshResource : () { |e}~> ()
fun freshResource() {
  escape esc in {
    sig k : () { |e}~> String
    fun k() {esc(())}
    redirect("?_k=" ^^ unsafePickleCont(k)); exit([])
  }
}
```
This works by forcing the continuation to have the same effect type as the ambient `freshResource` function.  However, I'm not 100% certain my initial approach of reusing the escape continuation type's effect for the effect of the argument to CallCC is correct either.

**Comment by jamescheney** [comment]
Perhaps what this indicates is that (after fixing the initial problem with the effect types getting out of sync in the translation to IR) we still need to constrain that the effect of the continuation `esc` equals the ambient effect where the `escape` operation takes place.  That is, if `escape` were a function instead of a builtin, it should have type
```
escape : ((a) { |e}~> b) { |e}~> a
```
but it is being treated as if it had this type instead:
```
escape : ((a) { |e1}~> b) { |e2}~> a
```
so there is no constraint on the continuation's effect other than that it be wild.  The first type logically should be what we want because the body of the `escape` may call the continuation, thus its effect should equal that of the ambient context.

Perhaps just fixing this would fix the original problem, since it should also ensure that the ambient effect that had been being used for the translation to CallCC is the same as the effect on the escape continuation.

**Comment by jamescheney** [comment]
After extensive staring at what I think are sensible typing rules for escape and call/cc, I'm no longer convinced what I had in mind to fix this is correct: I now think there is no reason the effect of the escape continuation has to match that of the calling context (e.g. if the escape continuation is never called).

There seems to be something strange going on with the `unsafePickleCont` library function, whose type is
```
(() { |e}-> a) ~> String
```
and which is used to define `pickleCont` as well as in `freshResource`.
```
sig pickleCont : (() { |e}-> Page) ~> String
fun pickleCont(cont) {unsafePickleCont(fun () {cont()})}
```
if I read these types right, both take a function that can have any effect, and produces a string, generating any other (wild) effect.  This makes sense, because whatever effects teh continuation has will not take place until the string is deserialized and called, but it does mean that the effect (and, for the unsafe one, the result type) are free type variables that don't necessarily get unified with anything else.

For whatever reason, this seems to lead to problems after translation to IR, even without using escape to create the continuation to pass to `unsafePickleCont`.  For example, this:
```
unsafePickleCont(fun () { () })
```
yields an IR typing error, even in `master`:

```
Row variable where row expected:(Types.Meta
   Point @ 0x10e68bcb8 (Types.Var
                          (355,
                           (CommonTypes.PrimaryKind.Row,
                            (CommonTypes.Linearity.Unl,
                             CommonTypes.Restriction.Any)),
                           `Rigid)))
([(Ir.Fun
     ((227, (forall 355::Row.() -355-> (), "_fun__g1", Var.Scope.Local)),
      ([(355,
         (CommonTypes.PrimaryKind.Row,
          (CommonTypes.Linearity.Unl, CommonTypes.Restriction.Any)))
         ],
       [], ([], (Ir.Return (Ir.Extend ({}, None))))),
      None, CommonTypes.Location.Unknown, false))
   ],
 (Ir.Apply ((Ir.TApp ((Ir.Variable 172), [{ |355 }; (); {  }])),
    [(Ir.TApp ((Ir.Variable 227), [{ |355 }]))])))
typechecking IR
Row variable where row expected:(Types.Meta
   Point @ 0x10e68bcb8 (Types.Var
                          (355,
                           (CommonTypes.PrimaryKind.Row,
                            (CommonTypes.Linearity.Unl,
                             CommonTypes.Restriction.Any)),
                           `Rigid)))
***: IR Type Error: Type variable 355 is unbound
occurring in IR tail computation:
(Ir.Apply ((Ir.TApp ((Ir.Variable 172), [{ |355 }; (); {  }])),
   [(Ir.TApp ((Ir.Variable 227), [{ |355 }]))])) 
```

again with a "row variable where row expected" warning.  But weirdly, the following equivalent-seeming code:
```
fun foo () { () }
unsafePickleCont(foo)
```
typechecks fine; the raw IR looks like this:
```
([(Ir.Fun
     ((227, (forall 350::Row.() -350-> (), "foo", Var.Scope.Global)),
      ([(350,
         (CommonTypes.PrimaryKind.Row,
          (CommonTypes.Linearity.Unl, CommonTypes.Restriction.Any)))
         ],
       [], ([], (Ir.Return (Ir.Extend ({}, None))))),
      None, CommonTypes.Location.Unknown, false))
   ],
 (Ir.Apply ((Ir.TApp ((Ir.Variable 172), [{ |%357 }; (); {  }])),
    [(Ir.TApp ((Ir.Variable 227), [{ |%357 }]))])))
```
possibly indicating the problem is avoided by let-generalizing the function before passing it to `unsafePickleCont`.

**Comment by jamescheney** [comment]
Also weirdly, this works:
```
sig bar : ((() -e-> ()) ~f~> String) ~f~> String
fun bar(upc) {
  upc(fun () { () })
}
bar(unsafePickleCont)
```
and likewise, this version of `freshResource` works:
```
sig freshResource0 : ((() ~e~> a) ~f~> String) ~f~> ()
fun freshResource0(upc) {
  escape esc in {
    redirect("?_k=" ^^ upc(fun () {esc(())})); exit([])
  }
}
sig freshResource : () ~> ()
fun freshResource() {freshResource0(unsafePickleCont)}
```
(both in master, that is 8e5eb97)

In both cases, we lambda-abstract over the library function `unsafePickleCont` so that it is represented by a (monomorphic) variable, and then pass it in.

**Comment by jamescheney** [comment]
NB: These errors all seem to be caught after closure conversion, but the IR typechecks before closure conversion.  So the problem may be partly to do with closure conversion of polymorphic functions.

**Comment by jstolarek** [comment]
Is it possible that `Row variable where row expected` error is related to #871? I've seen this when fixing #882 (see https://github.com/links-lang/links/pull/891#issuecomment-656093457). I was hoping for a moment that with `recheck_frontend_transformations=true` this error might get hidden, but apparently that's not the case.

Also, seeing `Type variable 355 is unbound` makes me sad. I thought we fixed all of those.

**Comment by jamescheney** [comment]
Not sure, but I am suspicious that there is something funny going on with library functions that have polymorphic types...

**Comment by slindley** [comment]
The `Row variable where row expected` debug message is related to the types refactoring (#637) - which I will return to once I have more time at the end of July. Basically, I'd hoped that we could maintain the invariant that types of kind `Row` in instantiation maps would always actually be rows. Sometimes they're actually row variables instead, but I couldn't work out where these were being introduced, so I just made sure to lift them to rows where necessary (accompanied by a warning).

**Comment by slindley** [comment]
I don't have time to look now, but I won't be surprised if what you're seeing here is just another instance of the problem with generalisation I alluded to in the discussion of #865.

**Comment by jamescheney** [comment]
OK.  I'll leave it alone for now.

**Comment by jstolarek** [comment]
I'm wondering whether the fix in `issue-873` branch is a fix worth having? It does fix incorrect handling of effects, doesn't it?

**Comment by jamescheney** [comment]
I'd hold off - I think it may mask the real problem by over-specializing the translation of `escape`.

**Comment by frank-emrich** [comment]
@jamescheney 
> NB: These errors all seem to be caught after closure conversion, but the IR typechecks before closure conversion. So the problem may be partly to do with closure conversion of polymorphic functions.

I'm not quite sure what you mean. The last example you give that fails seems to be
```
unsafePickleCont(fun () { () })
```
This rightfully fails IR type-checking before and after closure conversion (closure conversion should have no effect anyway in this example). This is due to the mismatch of the effects discussed earlier.

The next example:
```
sig bar : ((() -e-> ()) ~f~> String) ~f~> String
fun bar(upc) {
  upc(fun () { () })
}
bar(unsafePickleCont)
```
passes the IR type-checker (which normally runs before closure-conversion), but it still passes if I change things to re-run the IR type-checker after closure conversion.


In general, it would be very helpful to number the various examples throughout threads like this. Otherwise, it becomes very difficult to clarify which examples we are talking about.

**Comment by jamescheney** [comment]
Sorry, I was trying a lot of different things and didn't think to number things.  We could edit the comments to add numbers...

I believe the current state of this is that we believe it is not a problem with IR typechecking or closure conversion, but may be caused by a known problem with generalization #871 (the problem @slindley alluded to in #865).  So this should be revisited after #871 is resolved.
