### ISSUE TITLE
Can we make the typechecking of unsafe functions more flexible?

### ISSUE THREAD

**Issue by wricciot** [links-lang/links#929]
Hi,

The set+bag branch of Links relies on a deduplication function defined in the prelude as 

```
unsafe sig dedup : ([a]) -> [a]
fun dedup(l) server {
  fun aux(vl, rl) {
    switch (rl) {
      case [] -> []
      case r::rl0 ->
        if (r `elem` vl)
          aux(vl, rl0)
        else 
          r::aux(r::vl, rl0)
    }
  }
  aux([]:[a], l) 
}
```

With an `unsafe` annotation to convince Links that, despite the recursion, this function should be treated as tame (making it possible to use it in DB queries). This definition used to be accepted, but it currently doesn't typecheck any more (perhaps due to changes made in #864).
```
/home/barobaro/Links/links/_build/default/lib/prelude.links:526: Type error: The function
    `aux'
has type
    `([a], [a]) ~b~> [a]'
while the arguments passed to it have types
    `[a]'
and
    `[a]'
and the currently allowed effects are
    `|c'
In expression: aux([]:[a], l).
```

I am not completely sure why this error is raised, but it seems to have something to do with the fact that `unsafe` specifies `dedup` to be tame, while the real recursive function is the local definition `aux`. Furthermore, `aux` uses a list membership test `elem` whose type is also wild not only because of recursion, but also because the `tl` function used in it is wild.
```
fun elem(x, l) {
  not(l==[]) && (x == hd(l) || x `elem` tl(l))
}
elem = fun : (a, [a]) ~> Bool
```

In order for everything to typecheck correctly, I need to make both `elem` and `aux` tame (and the new definition of `elem` should not rely on `tl`). 
```
unsafe sig elem : (a,[a]) -b-> Bool
fun elem(x, l) {
  switch (l) {
    case [] -> false
    case hd::tl -> x == hd || x `elem` tl
  }
}

fun dedup(l) server {
  unsafe sig aux : ([a],[a]) -> [a]
  fun aux(vl, rl) {
    switch (rl) {
      case [] -> []
      case r::rl0 ->
        if (r `elem` vl)
          aux(vl, rl0)
        else 
          r::aux(r::vl, rl0)
    }
  }
  aux([]:[a], l) 
}
```

To me, it feels there's something wrong with this. First, the requirement that all function calls in an unsafe declaration should be tame is (unnecessarily?) strict; furthermore, by making `elem` tame we are also stating that it should make sense to use it within a query, so we must provide an SQL translation for it (which maybe makes sense, but as of now we don't do it). Generally speaking, I don't see why I should define `elem` to be tame if I'm only interested in `dedup` being tame.

What do you think?

**Comment by jamescheney** [comment]
Yes, I think the above definition of `dedup` is inferred to have a wild type because `elem` is wild.  The new behavior of `unsafe` is to disable.  This is still "unsafe" because one could easily use it to define tame functions that correspond ot recursive functions that are not definable on the database: to use `unsafe` safely we also need to make sure that any calls to such functions that wind up in queries are eventually substituted with equivalent query behavior.

This should be possible for both `elem` and `dedup`.  In fact `elem` is definable tamely and without using `unsafe`:

```
fun elem(x,xs) {
  not(empty(for (y <- xs) where (x == y) [()]))
}
```

so one strategy could be to inline this tame definition of `elem` into `dedup` and only use `unsafe` on the definition of `aux`.  (Of course the above definition of `elem` would also be correct at the top level, it's just potentially not as efficient as the one based on pattern matching, depending on how smart Links is about optimizing comprehension-style code in memory - my guess is, by default not very.)

**Comment by wricciot** [comment]
Yes, that'll work. However I don't understand what we gain from using an alternate, less efficient definition of the membership test within the deduplication function: if `dedup `is used in a database context, it'll be replaced by the corresponding SQL statement in its entirety; if however it is executed in memory, then we should want to use an efficient implementation of `elem`.

So, I guess the best implementation becomes the one in which the `elem` function used within `dedup` has the same implementation as the standard `elem`, with an additional `unsafe` annotation.

The previous behaviour in which the `unsafe` annotation was applied to functions that can be executed on the DB rather than on its pieces was more natural to me, but I get that there are other valid reasons for the new behaviour and I don't want to insist.

**Comment by jamescheney** [comment]
that makes sense.  The current treatment of `unsafe` is admittedly a hack, it's just a slightly more convenient hack than before, because it plays more nicel ywith type inference and doesn't require us to do lots of post hoc surgery to adapt the inferred type to match the ascribed one.  Effectively, we take advantage of the fact that if a function is tame, but also has an equivalent recursive definition, then we may use the equivalent recursive definition as if the recursive call is tame.  (what is "unsafe" is that we are not rigorously checking the first part.)

My observation that `elem` has a tame definition implies that if we wanted, we could give `elem` an unsafe signature and then replace any copies of it that appear in query expressions with the tame definition.  To avoid this, we could instead use a local unsafe copy of `elem` inside `dedup`: this local definition of `elem` should never appear in query expressions, because we will treat `dedup` itself specially and never expand it.  The local `elem` should only ever be called from program code.

```
sig elem : (a,[a]) ~b~> Bool
fun elem(x, l) {
  switch (l) {
    case [] -> false
    case hd::tl -> x == hd || x `elem` tl
  }
}

fun dedup(l) server {
  # an unsafe, local definition of elem, only for use within dedup
  unsafe sig elem : (a,[a]) -b-> Bool
  fun elem(x, l) {
    switch (l) {
      case [] -> false
      case hd::tl -> x == hd || x `elem` tl
    }
  }
  unsafe sig aux : ([a],[a]) -> [a]
  fun aux(vl, rl) {
    switch (rl) {
      case [] -> []
      case r::rl0 ->
        if (r `elem` vl)
          aux(vl, rl0)
        else 
          r::aux(r::vl, rl0)
    }
  }
  aux([]:[a], l) 
}
```

**Comment by wricciot** [comment]
Thank you @jamescheney, I'll mark this as closed.
