### ISSUE TITLE
Release 0.9.3 this week

### ISSUE THREAD

**Issue by dhil** [links-lang/links#961]
We agreed to prepare the release of 0.9.3 this week.

**Comment by dhil** [comment]
The release is underway opam-repository/#18775

**Comment by jamescheney** [comment]
Are you planning to publish the new links-mysql8 library as part of this release?

I now have slight misgivings about the approach of having two libraries (#963) so it might be good to hold off for now in case we think of a better way to do things.

**Comment by dhil** [comment]
It is part of the release, yes. Do you want me to retract the release?

**Comment by dhil** [comment]
Actually I didn't choose to make it part of the release, the release tool did. I think it bundles all *.opam files up into a release

**Comment by jamescheney** [comment]
Ah, OK.  So we could block this (for the time being) by renaming `links-mysql8.opam` to to `links-mysql8.opam.nonrelease` for now.

Having looked around, it does seem that there is supposed to be compatibility between recent versions of libmysqlclient and older MySQL servers, but it is somewhat limited/buggy.  The thing I'd like to avoid is publishing a links-mysql8 library and eventually having to deprecate it (or deprecate the existing links-mysql library), but given the current state of ocaml mysql drivers this may be unavoidable.  Given that we have no evidence that people out there in the vast Links user community are relying on links-mysql or clamoring for links-mysql8 it is probably fine either way, but my inclination would be to delay making a release that depends on ocaml-mysql8 since perhaps in the not too distant future ocaml-mysql will evolve to support MySQL8.

**Comment by dhil** [comment]
OK. I will retract the release, I don't think it has been upstreamed yet.

**Comment by jamescheney** [comment]
Thanks!

**Comment by dhil** [comment]
I will try to package a new release now without links-mysql8

**Comment by dhil** [comment]
New release is underway ocaml/opam-repository#18781.

For some reason the change log doesn't render properly when viewed in the "Release" section of GitHub, but it looks fine in `CHANGES.md`. I gave up on trying to fix the issue, it is probably some silly markdown ambiguity.

**Comment by dhil** [comment]
Update: I manually copy-pasted the change log into the release section. Seems like it did the trick.

**Comment by dhil** [comment]
The release process has been simplified quite a bit. I have updated https://github.com/links-lang/links/wiki/Release-checklist to reflect the new process.
